In [ ]:
'''A partir del csv hospitales2.csv, generar un archivo CSV de salida,
que contenga los siguientes campos en este orden:
* latitude
* longitude
* name
* label
Con los correspondientes datos extraídos del CSV original, el campo name
tiene que corresponder con la dirección del hospital, y el campo label con
el nombre del hospital.'''

'A partir del csv hospitales2.csv, generar un archivo CSV de salida, \nque contenga los siguientes campos en este orden:\n* latitude\n* longitude\n* name\n* label\nCon los correspondientes datos extraídos del CSV original, el campo name\ntiene que corresponder con la dirección del hospital, y el campo label con\nel nombre del hospital.'

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv(r'/content/drive/MyDrive/cursos-para-dictar/UDM/04_clase/hospitales2.csv', sep = ',')
'''Acá si no quieren que se vea todo, "abreviamos" la impresión del dataset
con df.head()'''
df.head()

,WKT,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,POINT (-58.3775508488443 -34.6288473603881),1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,POINT (-58.4120700769456 -34.5941919726393),2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo
2,POINT (-58.4027276547828 -34.5845283357505),4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,4805-6407,4805-7533,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti
3,POINT (-58.3851559118889 -34.6394041316484),6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,4301-4522,4303-3655/59,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito
4,POINT (-58.3913114406535 -34.6341535760002),7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,4306-4641 al 49 (int. 125),4306-3013,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa

` Un poco de ETL ó "Data Wrangling". Dejo el enlace de donde saqué la respuesta:
`

[Reemplazar valores de una columna en pandas](https://stackoverflow.com/questions/37593550/replace-method-not-working-on-pandas-dataframe)

In [6]:
df["WKT"]= df.WKT.str.replace('POINT', '')
df["WKT"]= df.WKT.str.replace('(', '')
df["WKT"]= df.WKT.str.replace(')', '')
df.head()

,WKT,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,-58.3775508488443 -34.6288473603881,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,-58.4120700769456 -34.5941919726393,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo
2,-58.4027276547828 -34.5845283357505,4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,4805-6407,4805-7533,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti
3,-58.3851559118889 -34.6394041316484,6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,4301-4522,4303-3655/59,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito
4,-58.3913114406535 -34.6341535760002,7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,4306-4641 al 49 (int. 125),4306-3013,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa

`How to rename columns in pandas(with examples)`

[Como cambiar el nombre de las columnas en Pandas](https://www.statology.org/pandas-rename-columns/)

In [7]:
df.rename(columns = {'WKT':'Coordenadas'}, inplace = True)
df.head(2)

,Coordenadas,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,-58.3775508488443 -34.6288473603881,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,-58.4120700769456 -34.5941919726393,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo

In [8]:
'''Primero acá me salía un error porque no me daba cuenta que en la columna "Coordenadas" hay un espacio
adelante de las coordenadas y un espacio entre medio, por lo que geométricamente,
por así decirlo, el script lo separa en 3 columnas. Y yo lo separaba en dos solamente.
Ahora miremos el error'''
df[['Latitude', 'Longitude']] = df['Coordenadas'].str.split(' ', expand=True)

'''Aparece el value error que dice que las columnas deben tener el mismo largo que la llave, osea que,
las columnas que estan siendo separadas'''

ValueError: Columns must be same length as key

In [9]:
split_counts = df['Coordenadas'].str.split(' ').apply(len)
print(split_counts.value_counts())

Coordenadas
3    36
Name: count, dtype: int64

In [10]:
print(df['Coordenadas'].head(10))

0     -58.3775508488443 -34.6288473603881
1     -58.4120700769456 -34.5941919726393
2     -58.4027276547828 -34.5845283357505
3     -58.3851559118889 -34.6394041316484
4     -58.3913114406535 -34.6341535760002
5     -58.4349433479819 -34.6084721257413
6     -58.3758433488021 -34.6302112044495
7     -58.3823284509488 -34.6357022351559
8     -58.3821283746958 -34.6364350546569
9     -58.3601201271455 -34.6388917320834
Name: Coordenadas, dtype: object

In [11]:
df2 = df.copy()

In [12]:
'''Acá tenemos la misma dimensión y luego funciona'''
df[[' ','Latitude', 'Longitude']] = df['Coordenadas'].str.split(' ', expand=True)

In [13]:
df.columns

Index(['Coordenadas', 'ID', 'NOMBRE', 'NOM_MAP', 'OBJETO', 'CALLE', 'ALTURA',
       'DOM_NORMA', 'DOM_GEO', 'TELEFONO', 'GUARDIA', 'FAX', 'WEB',
       'COD_POSTAL', 'TIPO', 'TIPO_ESPEC', 'MOD_AT_1', 'MOD_AT_2',
       'DEPEND_ADM', 'DIRECTOR', ' ', 'Latitude', 'Longitude'],
      dtype='object')

In [ ]:
# Otra forma de hacerlo sería:

df2[['Latitude', 'Longitude']] = df2['Coordenadas'].str.strip().str.split(expand=True) # sp

### Atención !
----->
[De acá me robé el código anterior 😂👍](https://datascienceparichay.com/article/pandas-split-column-by-delimiter/#:~:text=Split%20column%20by%20delimiter%20into,True%20to%20the%20expand%20parameter.)<-----

In [ ]:
'''Volvemos a mostrar el dataframe y ahora lo que habría que hacer es eliminarle esa columna sin nada
y la columna de Coordenadas'''
df.head()

,Coordenadas,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,...,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR,,Latitude,Longitude
0,-58.3775508488443 -34.6288473603881,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,...,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart,,-58.3775508488443,-34.6288473603881
1,-58.4120700769456 -34.5941919726393,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,...,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo,,-58.4120700769456,-34.5941919726393
2,-58.4027276547828 -34.5845283357505,4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,...,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti,,-58.4027276547828,-34.5845283357505
3,-58.3851559118889 -34.6394041316484,6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,...,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito,,-58.3851559118889,-34.6394041316484
4,-58.3913114406535 -34.6341535760002,7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,...,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa,,-58.3913114406535,-34.6341535760002

In [ ]:
del df[' ']
del df['Coordenadas']

In [ ]:
'''Ahora vemos que el dataframe, pasó de 5 filas x 23 columnas a 5 filas x 21 columnas
   Borramos las columnas innecesarias.
   Me gustaría ordenar, sólo de caprichoso, el dataframe como estaba al inicio. La latitud y longitud al
   inicio del dataframe y no al final como está ahora.
'''
df.head()

,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,...,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR,Latitude,Longitude
0,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,...,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart,-58.3775508488443,-34.6288473603881
1,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,...,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo,-58.4120700769456,-34.5941919726393
2,4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,4805-6407,...,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti,-58.4027276547828,-34.5845283357505
3,6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,4301-4522,...,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito,-58.3851559118889,-34.6394041316484
4,7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,4306-4641 al 49 (int. 125),...,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa,-58.3913114406535,-34.6341535760002

[Como reordenar columnas?](https://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns)

`Primero ver la lista de columnas, cosa de que sea más fácil hacerlo manualmente. Luego copiar y pegarlas, y asignarle el orden deseado.`

In [ ]:
'''Así vemos las columnas en forma de lista: '''
columnas = list(df.columns.values)
columnas

['ID',
 'NOMBRE',
 'NOM_MAP',
 'OBJETO',
 'CALLE',
 'ALTURA',
 'DOM_NORMA',
 'DOM_GEO',
 'TELEFONO',
 'GUARDIA',
 'FAX',
 'WEB',
 'COD_POSTAL',
 'TIPO',
 'TIPO_ESPEC',
 'MOD_AT_1',
 'MOD_AT_2',
 'DEPEND_ADM',
 'DIRECTOR',
 'Latitude',
 'Longitude']

In [ ]:
'''Acá definimos el nuevo orden de las columnas'''

df = df[['Latitude',
    'Longitude',
    'ID',
 'NOMBRE',
 'NOM_MAP',
 'OBJETO',
 'CALLE',
 'ALTURA',
 'DOM_NORMA',
 'DOM_GEO',
 'TELEFONO',
 'GUARDIA',
 'FAX',
 'WEB',
 'COD_POSTAL',
 'TIPO',
 'TIPO_ESPEC',
 'MOD_AT_1',
 'MOD_AT_2',
 'DEPEND_ADM',
 'DIRECTOR']]

In [ ]:
'''Nuevo orden: '''
df.head()

,Latitude,Longitude,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,...,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,-58.3775508488443,-34.6288473603881,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",...,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,-58.4120700769456,-34.5941919726393,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,...,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo
2,-58.4027276547828,-34.5845283357505,4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,...,4805-6407,4805-7533,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti
3,-58.3851559118889,-34.6394041316484,6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,...,4301-4522,4303-3655/59,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito
4,-58.3913114406535,-34.6341535760002,7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,...,4306-4641 al 49 (int. 125),4306-3013,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa

In [ ]:
df_pedido = df[['Longitude',
    'Latitude',
    'NOMBRE',
    'DOM_NORMA']]

In [ ]:
df_pedido.rename(columns = {'NOMBRE':'Label','DOM_NORMA':'Name'}, inplace = True)

C:\Users\Alfredo\anaconda3\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_pedido = df_pedido[['Longitude', 'Latitude', 'Name', 'Label']]
df_pedido

,Longitude,Latitude,Name,Label
0,-34.6288473603881,-58.3775508488443,"MONTES DE OCA, MANUEL AV. 40",HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE
1,-34.5941919726393,-58.4120700769456,GALLO 1330,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ
2,-34.5845283357505,-58.4027276547828,SANCHEZ DE BUSTAMANTE 2529,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...
3,-34.6394041316484,-58.3851559118889,BRANDSEN 2570,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO
4,-34.6341535760002,-58.3913114406535,CASEROS AV. 2061,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO
5,-34.6084721257413,-58.4349433479819,DIAZ VELEZ AV. 4821,INSTITUTO DE ZOONOSIS L. PASTEUR
6,-34.6302112044495,-58.3758433488021,FINOCHIETTO ENRIQUE DR. 849,HOSPITAL DE REHABILITACION RESPIRATORIA MARIA ...
7,-34.6357022351559,-58.3823284509488,"CARRILLO, RAMON, DR. 315",HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA
8,-34.6364350546569,-58.3821283746958,"CARRILLO, RAMON, DR. 375",HOSPITAL DE SALUD MENTAL J. T. BORDA
9,-34.6388917320834,-58.3601201271455,DON PEDRO DE MENDOZA AV. 1795,HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QU...
10,-34.5538963316473,-58.4409882382439,ECHEVERRIA 955,INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E...
11,-34.634856308415,-58.4027506275377,"LUCA, ESTEBAN DE 2151",HOSPITAL MATERNO INFANTIL R. SARDA
12,-34.6054342750207,-58.4601855775528,"JUSTO, JUAN B. AV. 4151",HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE
13,-34.6146348348429,-58.4276597542837,MUÑIZ 15,HOSPITAL DE ODONTOLOGIA JOSE DUEÑAS
14,-34.6070507603866,-58.4332484381295,PATRICIAS ARGENTINAS AV. 150,HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE
15,-34.6255031952483,-58.4323966950244,"GOYENA, PEDRO AV. 369",HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA
16,-34.6227125075124,-58.3940641604746,SAN JUAN AV. 2021,HOSPITAL DE OFTALMOLOGIA SANTA LUCIA
17,-34.6179817540591,-58.5021449222222,SEGUROLA AV. 1949,HOSPITAL DE REHABILITACION M. ROCCA
18,-34.6375293258416,-58.3937269413225,USPALLATA 2272,HOSPITAL DE INFECCIOSAS F. MUÑIZ
19,-34.5972098729151,-58.4752588459761,WARNES AV. 2630,HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO...
20,-34.5847659581214,-58.4005134574423,LAS HERAS GENERAL AV. 2670,HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA
21,-34.6283448581677,-58.365985088719,PI Y MARGALL 750,HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH
22,-34.581141710889,-58.4068939142787,CERVIÑO AV. 3356,HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ
23,-34.6089728538414,-58.437981361705,DIAZ VELEZ AV. 5044,HOSPITAL GENERAL DE AGUDOS DR. C. DURAND
24,-34.6241704940114,-58.4695020363265,"ARANGUREN, JUAN F., DR. 2701",HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ
25,-34.6176598438607,-58.4096107488155,"URQUIZA, GRAL. 609",HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA
26,-34.565051956568,-58.4710781593251,MONROE AV. 3555,HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO
27,-34.599979524264,-58.5110525000569,NUEVA YORK 3952,HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA
28,-34.6253367952668,-58.50761514092,"CALDERON DE LA BARCA, PEDRO 1550",HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD
29,-34.6491867281064,-58.5156291936709,PILAR 950,HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI
30,-34.6431172591975,-58.4108602188291,"CHUTRO, PEDRO, PROF., DR. 3380",HOSPITAL GENERAL DE AGUDOS J. A. PENNA
31,-34.5873917690227,-58.4710976282168,COMBATIENTES DE MALVINAS AV. 3002,HOSPITAL GENERAL DE AGUDOS DR. E. TORNU
32,-34.643894071866,-58.4541167814714,VARELA AV. 1301,HOSPITAL GENERAL DE AGUDOS P. PIÑERO
33,-34.6718480140772,-58.4566428491103,"FERNANDEZ DE LA CRUZ, F., GRAL. 4402",HOSPITAL CECILIA GRIERSON
34,-34.6299453614404,-58.3918791813882,COMBATE DE LOS POZOS 1881,HOSP. DE PEDIATRIA DR. J. GARRAHAN
35,-34.6419888014928,-58.3814293381891,SUAREZ AV. 2215,TALLERES PROTEGIDOS DE REHABILITACION PSIQUIAT...

In [ ]:
'''Les cambié el orden, porque cuando lo imprimia en https://www.gpsvisualizer.com/map?output_home
me tiraba las direcciones en el medio del oceano'''
df_pedido = df_pedido.rename(columns={'Longitude':'Latitude',
                                   'Latitude':'Longitude'})

df_pedido.columns

Index(['Longitude', 'Latitude', 'Name', 'Label'], dtype='object')

In [ ]:
df_pedido

,Latitude,Longitude,Name,Label
0,-34.6288473603881,-58.3775508488443,"MONTES DE OCA, MANUEL AV. 40",HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE
1,-34.5941919726393,-58.4120700769456,GALLO 1330,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ
2,-34.5845283357505,-58.4027276547828,SANCHEZ DE BUSTAMANTE 2529,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...
3,-34.6394041316484,-58.3851559118889,BRANDSEN 2570,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO
4,-34.6341535760002,-58.3913114406535,CASEROS AV. 2061,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO
5,-34.6084721257413,-58.4349433479819,DIAZ VELEZ AV. 4821,INSTITUTO DE ZOONOSIS L. PASTEUR
6,-34.6302112044495,-58.3758433488021,FINOCHIETTO ENRIQUE DR. 849,HOSPITAL DE REHABILITACION RESPIRATORIA MARIA ...
7,-34.6357022351559,-58.3823284509488,"CARRILLO, RAMON, DR. 315",HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA
8,-34.6364350546569,-58.3821283746958,"CARRILLO, RAMON, DR. 375",HOSPITAL DE SALUD MENTAL J. T. BORDA
9,-34.6388917320834,-58.3601201271455,DON PEDRO DE MENDOZA AV. 1795,HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QU...
10,-34.5538963316473,-58.4409882382439,ECHEVERRIA 955,INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E...
11,-34.634856308415,-58.4027506275377,"LUCA, ESTEBAN DE 2151",HOSPITAL MATERNO INFANTIL R. SARDA
12,-34.6054342750207,-58.4601855775528,"JUSTO, JUAN B. AV. 4151",HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE
13,-34.6146348348429,-58.4276597542837,MUÑIZ 15,HOSPITAL DE ODONTOLOGIA JOSE DUEÑAS
14,-34.6070507603866,-58.4332484381295,PATRICIAS ARGENTINAS AV. 150,HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE
15,-34.6255031952483,-58.4323966950244,"GOYENA, PEDRO AV. 369",HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA
16,-34.6227125075124,-58.3940641604746,SAN JUAN AV. 2021,HOSPITAL DE OFTALMOLOGIA SANTA LUCIA
17,-34.6179817540591,-58.5021449222222,SEGUROLA AV. 1949,HOSPITAL DE REHABILITACION M. ROCCA
18,-34.6375293258416,-58.3937269413225,USPALLATA 2272,HOSPITAL DE INFECCIOSAS F. MUÑIZ
19,-34.5972098729151,-58.4752588459761,WARNES AV. 2630,HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO...
20,-34.5847659581214,-58.4005134574423,LAS HERAS GENERAL AV. 2670,HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA
21,-34.6283448581677,-58.365985088719,PI Y MARGALL 750,HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH
22,-34.581141710889,-58.4068939142787,CERVIÑO AV. 3356,HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ
23,-34.6089728538414,-58.437981361705,DIAZ VELEZ AV. 5044,HOSPITAL GENERAL DE AGUDOS DR. C. DURAND
24,-34.6241704940114,-58.4695020363265,"ARANGUREN, JUAN F., DR. 2701",HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ
25,-34.6176598438607,-58.4096107488155,"URQUIZA, GRAL. 609",HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA
26,-34.565051956568,-58.4710781593251,MONROE AV. 3555,HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO
27,-34.599979524264,-58.5110525000569,NUEVA YORK 3952,HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA
28,-34.6253367952668,-58.50761514092,"CALDERON DE LA BARCA, PEDRO 1550",HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD
29,-34.6491867281064,-58.5156291936709,PILAR 950,HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI
30,-34.6431172591975,-58.4108602188291,"CHUTRO, PEDRO, PROF., DR. 3380",HOSPITAL GENERAL DE AGUDOS J. A. PENNA
31,-34.5873917690227,-58.4710976282168,COMBATIENTES DE MALVINAS AV. 3002,HOSPITAL GENERAL DE AGUDOS DR. E. TORNU
32,-34.643894071866,-58.4541167814714,VARELA AV. 1301,HOSPITAL GENERAL DE AGUDOS P. PIÑERO
33,-34.6718480140772,-58.4566428491103,"FERNANDEZ DE LA CRUZ, F., GRAL. 4402",HOSPITAL CECILIA GRIERSON
34,-34.6299453614404,-58.3918791813882,COMBATE DE LOS POZOS 1881,HOSP. DE PEDIATRIA DR. J. GARRAHAN
35,-34.6419888014928,-58.3814293381891,SUAREZ AV. 2215,TALLERES PROTEGIDOS DE REHABILITACION PSIQUIAT...

In [ ]:
type(df_pedido['Longitude'][0])

str

In [ ]:
df_pedido['Latitude'] = pd.to_numeric(df_pedido['Latitude'], downcast='float')

In [ ]:
df_pedido['Longitude'] = pd.to_numeric(df_pedido['Longitude'], downcast='float')

In [ ]:
print(type(df_pedido['Longitude'][0]))
print(type(df_pedido['Latitude'][0]))

<class 'numpy.float32'>
<class 'numpy.float32'>

In [ ]:
'''Es muy importante, poner el index = False. Porque si no se exporta con una coma y un indice adelante'''

df_pedido.to_csv(r'C:\Users\Alfredo\Bitácoras\SoyHenry\DS-M1\Clase 04\Pandascoordenadas.csv', index = False)

### Otra forma de hacerlo sin usar Pandas

In [ ]:
archivo = open(r'C:\Users\Alfredo\Bitácoras\SoyHenry\DS-M1\Clase 04\hospitales2.csv', encoding = 'utf-8')
tabla = csv.reader(archivo)
with open(r'C:\Users\Alfredo\Bitácoras\SoyHenry\DS-M1\Clase 04\Coordenadas.csv', 'w', encoding = 'utf-8', newline = '') as salida:
    salida_writer = csv.writer(salida)
    next(tabla)
    salida_writer.writerow(['latitude','longitude', 'name', 'label'])
    for linea in tabla:
        '''Esta parte hace el ETL'''
        print (linea[0][7:-1])
        coordenadas = linea[0][7:-1].split()
        salida_writer.writerow([coordenadas[0], coordenadas [1], linea[8], linea[3]])

-58.3775508488443 -34.6288473603881
-58.4120700769456 -34.5941919726393
-58.4027276547828 -34.5845283357505
-58.3851559118889 -34.6394041316484
-58.3913114406535 -34.6341535760002
-58.4349433479819 -34.6084721257413
-58.3758433488021 -34.6302112044495
-58.3823284509488 -34.6357022351559
-58.3821283746958 -34.6364350546569
-58.3601201271455 -34.6388917320834
-58.4409882382439 -34.5538963316473
-58.4027506275377 -34.634856308415
-58.4601855775528 -34.6054342750207
-58.4276597542837 -34.6146348348429
-58.4332484381295 -34.6070507603866
-58.4323966950244 -34.6255031952483
-58.3940641604746 -34.6227125075124
-58.5021449222222 -34.6179817540591
-58.3937269413225 -34.6375293258416
-58.4752588459761 -34.5972098729151
-58.4005134574423 -34.5847659581214
-58.365985088719 -34.6283448581677
-58.4068939142787 -34.581141710889
-58.437981361705 -34.6089728538414
-58.4695020363265 -34.6241704940114
-58.4096107488155 -34.6176598438607
-58.4710781593251 -34.565051956568
-58.5110525000569 -34.599979524264
-58.50761514092 -34.6253367952668
-58.5156291936709 -34.6491867281064
-58.4108602188291 -34.6431172591975
-58.4710976282168 -34.5873917690227
-58.4541167814714 -34.643894071866
-58.4566428491103 -34.6718480140772
-58.3918791813882 -34.6299453614404
-58.3814293381891 -34.6419888014928

### Ahora vamos a tratar de hacer lo mismo con el método de los diccionarios. que vimos en la práctica de la clase 2
---> Un poco más complicado.

In [ ]:
import os
archivo = open(r'C:\Users\Alfredo\Bitácoras\SoyHenry\DS-M1\Clase 04\hospitales2.csv')
dicc = {'WKT': [],
        'ID': [],
        'NOMBRE': [],
        'NOM_MAP': [],
        'OBJETO': [],
        'CALLE': [],
        'ALTURA': [],
        'DOM_NORMA': [],
        'DOM_GEO': [],
        'TELEFONO': [],
        'GUARDIA': [],
        'FAX': [],
        'WEB': [],
        'COD_POSTAL': [],
        'TIPO': [],
        'TIPO_ESPEC': [],
        'MOD_AT_1': [],
        'MOD_AT_2': [],
        'DEPEND_ADM': [],
        'DIRECTOR': []}

In [ ]:
next(archivo)
for linea in archivo:
    linea = linea.strip()
    campos = linea.split(',')
    dicc['WKT'].append(campos[0])
    dicc['ID'].append(campos[1])
    dicc['NOMBRE'].append(campos[2])
    dicc['NOM_MAP'].append(campos[3])
    dicc['OBJETO'].append(campos[4])
    dicc['CALLE'].append(campos[5])
    dicc['ALTURA'].append(campos[6])
    dicc['DOM_NORMA'].append(campos[7])
    dicc['DOM_GEO'].append(campos[8])
    dicc['TELEFONO'].append(campos[9])
    dicc['GUARDIA'].append(campos[10])
    dicc['FAX'].append(campos[11])
    dicc['WEB'].append(campos[12])
    dicc['COD_POSTAL'].append(campos[13])
    dicc['TIPO'].append(campos[14])
    dicc['TIPO_ESPEC'].append(campos[15])
    dicc['MOD_AT_1'].append(campos[16])
    dicc['MOD_AT_2'].append(campos[17])
    dicc['DEPEND_ADM'].append(campos[18])
    dicc['DIRECTOR'].append(campos[19])

In [ ]:
llaves = dicc.keys()
llaves = list(llaves)

In [ ]:
for i in llaves:
    print(dicc[i][25])

"POINT (-58.4096107488155 -34.6176598438607)"
28.00000000000
HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA
HOSP. RAMOS MEJIA
HOSPITAL
GENERAL URQUIZA
"609"
"URQUIZA
 GRAL. 609"
"609 URQUIZA
 GRAL."
4127-0200 / 300
4127-0400
4932-8858
www.hospitalramosmejia.info
C1221ADC
Hospital de agudos
GRAL: BAS/CRIT/OTR
AT. AMB./INTERNACION
DIAG./TRATAM.

In [ ]:
'''Cuantas variables hay?'''
print('Tenemos:', len(dicc.keys()),'variables')

Tenemos: 20 variables

In [ ]:
'''Que tipos de datos usar para cada una'''
print('Vemos el tipo de datos que contiene el diccionario:\n')
for i in dicc:
    print(type(dicc[i]))
'''Vemos que cada una de las variables es una lista, porque se lo
declaramos en el paso anterior (en donde armamos el diccionario, creamos
20 listas distintas, dentro del diccionario)'''

'''Ahora vamos a ver el primer elemento de cada lista, para ver que tipo
de dato es:'''
print('\nVemos el tipo dato del primer elemento de la lista:\n')
for i in dicc:
    print(type(dicc[i][0]))

Vemos el tipo de datos que contiene el diccionario:

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>

Vemos el tipo dato del primer elemento de la lista:

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [ ]:
'''Ahora un poco de data wrangling ó ETL por así decirlo:
Le sacamos el "POINT a la lista de valores, y la otra comilla " al final.
Y guardamos los nuevos valores corregidos en una lista nueva, llamada coordenadas.'''
coordenadas = []
for elemento in (dicc['WKT']):
    elemento = elemento.replace('"POINT ','')
    elemento = elemento.replace('"','')
    elemento = elemento.replace('(', '')
    elemento = elemento.replace(')', '')
    coordenadas.append(elemento)

print (coordenadas)

['-58.3775508488443 -34.6288473603881', '-58.4120700769456 -34.5941919726393', '-58.4027276547828 -34.5845283357505', '-58.3851559118889 -34.6394041316484', '-58.3913114406535 -34.6341535760002', '-58.4349433479819 -34.6084721257413', '-58.3758433488021 -34.6302112044495', '-58.3823284509488 -34.6357022351559', '-58.3821283746958 -34.6364350546569', '-58.3601201271455 -34.6388917320834', '-58.4409882382439 -34.5538963316473', '-58.4027506275377 -34.634856308415', '-58.4601855775528 -34.6054342750207', '-58.4276597542837 -34.6146348348429', '-58.4332484381295 -34.6070507603866', '-58.4323966950244 -34.6255031952483', '-58.3940641604746 -34.6227125075124', '-58.5021449222222 -34.6179817540591', '-58.3937269413225 -34.6375293258416', '-58.4752588459761 -34.5972098729151', '-58.4005134574423 -34.5847659581214', '-58.365985088719 -34.6283448581677', '-58.4068939142787 -34.581141710889', '-58.437981361705 -34.6089728538414', '-58.4695020363265 -34.6241704940114', '-58.4096107488155 -34.6176598438607', '-58.4710781593251 -34.565051956568', '-58.5110525000569 -34.599979524264', '-58.50761514092 -34.6253367952668', '-58.5156291936709 -34.6491867281064', '-58.4108602188291 -34.6431172591975', '-58.4710976282168 -34.5873917690227', '-58.4541167814714 -34.643894071866', '-58.4566428491103 -34.6718480140772', '-58.3918791813882 -34.6299453614404', '-58.3814293381891 -34.6419888014928']

In [ ]:
'''Acá en el medio fui inventando y probando cosas.
Puede fallar 😂'''
#dicc['WKT'].replace(coordenadas)
index(coordenadas)

NameError: name 'index' is not defined

In [ ]:
'''De repente se me cayó una idea de hacer lo más simple y fácil. Decirle a Python que iguale la lista
WKT del diccionario a a lista que creamos recién.
Y al parecer, funcionó 👏👏👏'''
dicc['WKT'] = coordenadas
dicc['WKT']
dicc

{'WKT': ['-58.3775508488443 -34.6288473603881',
  '-58.4120700769456 -34.5941919726393',
  '-58.4027276547828 -34.5845283357505',
  '-58.3851559118889 -34.6394041316484',
  '-58.3913114406535 -34.6341535760002',
  '-58.4349433479819 -34.6084721257413',
  '-58.3758433488021 -34.6302112044495',
  '-58.3823284509488 -34.6357022351559',
  '-58.3821283746958 -34.6364350546569',
  '-58.3601201271455 -34.6388917320834',
  '-58.4409882382439 -34.5538963316473',
  '-58.4027506275377 -34.634856308415',
  '-58.4601855775528 -34.6054342750207',
  '-58.4276597542837 -34.6146348348429',
  '-58.4332484381295 -34.6070507603866',
  '-58.4323966950244 -34.6255031952483',
  '-58.3940641604746 -34.6227125075124',
  '-58.5021449222222 -34.6179817540591',
  '-58.3937269413225 -34.6375293258416',
  '-58.4752588459761 -34.5972098729151',
  '-58.4005134574423 -34.5847659581214',
  '-58.365985088719 -34.6283448581677',
  '-58.4068939142787 -34.581141710889',
  '-58.437981361705 -34.6089728538414',
  '-58.4695020363265 -34.6241704940114',
  '-58.4096107488155 -34.6176598438607',
  '-58.4710781593251 -34.565051956568',
  '-58.5110525000569 -34.599979524264',
  '-58.50761514092 -34.6253367952668',
  '-58.5156291936709 -34.6491867281064',
  '-58.4108602188291 -34.6431172591975',
  '-58.4710976282168 -34.5873917690227',
  '-58.4541167814714 -34.643894071866',
  '-58.4566428491103 -34.6718480140772',
  '-58.3918791813882 -34.6299453614404',
  '-58.3814293381891 -34.6419888014928'],
 'ID': ['1.00000000000',
  '2.00000000000',
  '4.00000000000',
  '6.00000000000',
  '7.00000000000',
  '8.00000000000',
  '9.00000000000',
  '10.00000000000',
  '11.00000000000',
  '12.00000000000',
  '13.00000000000',
  '14.00000000000',
  '15.00000000000',
  '16.00000000000',
  '17.00000000000',
  '18.00000000000',
  '19.00000000000',
  '20.00000000000',
  '21.00000000000',
  '22.00000000000',
  '23.00000000000',
  '24.00000000000',
  '25.00000000000',
  '26.00000000000',
  '27.00000000000',
  '28.00000000000',
  '29.00000000000',
  '30.00000000000',
  '31.00000000000',
  '32.00000000000',
  '33.00000000000',
  '34.00000000000',
  '35.00000000000',
  '36.00000000000',
  '3.00000000000',
  '5.00000000000'],
 'NOMBRE': ['HOSPITAL GENERAL DE NIÃ‘OS PEDRO DE ELIZALDE',
  'HOSPITAL GENERAL DE NIÃ‘OS RICARDO GUTIERREZ',
  'HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX NACIONAL)',
  'HOSPITAL DE SALUD MENTAL BRAULIO MOYANO',
  'HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO',
  'INSTITUTO DE ZOONOSIS L. PASTEUR',
  'HOSPITAL DE REHABILITACION RESPIRATORIA MARIA FERRER',
  'HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA',
  'HOSPITAL DE SALUD MENTAL J. T. BORDA',
  'HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QUINQUELA MARTIN',
  'INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E.P.)',
  'HOSPITAL MATERNO INFANTIL R. SARDA',
  'HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE',
  'HOSPITAL DE ODONTOLOGIA  JOSE DUEÃ‘AS',
  'HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE',
  'HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA',
  'HOSPITAL DE OFTALMOLOGIA SANTA LUCIA',
  'HOSPITAL DE REHABILITACION M. ROCCA',
  'HOSPITAL DE INFECCIOSAS F. MUÃ‘IZ',
  'HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO DE ALVEAR',
  'HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA',
  'HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH',
  'HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ',
  'HOSPITAL GENERAL DE AGUDOS DR. C. DURAND',
  'HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ',
  'HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA',
  'HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO',
  'HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA',
  'HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD',
  'HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI',
  'HOSPITAL GENERAL DE AGUDOS J. A. PENNA',
  'HOSPITAL GENERAL DE AGUDOS DR. E. TORNU',
  'HOSPITAL GENERAL DE AGUDOS P. PIÃ‘ERO',
  'HOSPITAL CECILIA GRIERSON',
  'HOSP. DE PEDIATRIA DR. J. GARRAHAN',
  'TALLERES PROTEGIDOS DE REHABILITACION PSIQUIATRICA'],
 'NOM_MAP': ['HOSP. DE ELIZALDE',
  'HOSP. GUTIERREZ',
  'HOSP. ODONTOLOGICO CARRILLO',
  'HOSP. MOYANO',
  'HOSP. UDAONDO',
  'INST. PASTEUR',
  'HOSP. FERRER',
  'HOSP. TOBAR GARCIA',
  'HOSP. BORDA',
  'HOSP. ODONTOLOGICO INFANTIL QUINQUELA MARTIN',
  'INST. DE REHAB. PSICOFISICA',
  'HOSP. SARDA',
  'HOSP. LAGLEYZE',
  'HOSP. ODONTOLOGICO DUEÃ‘AS',
  'HOSP. CURIE',
  'HOSP. DE QUEMADOS A. U. ILLIA',
  'HOSP. SANTA LUCIA',
  'HOSP. DE REHAB. ROCCA',
  'HOSP. MUÃ‘IZ',
  'HOSP. T. DE ALVEAR',
  'HOSP. RIVADAVIA',
  'HOSP. ARGERICH',
  'HOSP. FERNANDEZ',
  'HOSP. DURAND',
  'HOSP. ALVAREZ',
  'HOSP. RAMOS MEJIA',
  'HOSP. PIROVANO',
  'HOSP. ZUBIZARRETA',
  'HOSP. VELEZ SARSFIELD',
  'HOSP. SANTOJANNI',
  'HOSP. PENNA',
  'HOSP. TORNU',
  'HOSP. PIÃ‘ERO',
  'HOSP. GRIERSON',
  'HOSP. GARRAHAN',
  'TALLERES DE REHAB. PSIQUIATRICA'],
 'OBJETO': ['HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL'],
 'CALLE': ['MANUEL A. MONTES DE OCA',
  'GALLO',
  'SANCHEZ DE BUSTAMANTE',
  'BRANDSEN',
  'CASEROS',
  'DIAZ VELEZ',
  'DOCTOR ENRIQUE FINOCHIETTO',
  'DOCTOR RAMON CARRILLO',
  'DOCTOR RAMON CARRILLO',
  'DON PEDRO DE MENDOZA',
  'ECHEVERRIA',
  'ESTEBAN DE LUCA',
  'JUAN B. JUSTO',
  'MUÃ‘IZ',
  'PATRICIAS ARGENTINAS',
  'PEDRO GOYENA',
  'SAN JUAN',
  'SEGUROLA',
  'USPALLATA',
  'WARNES',
  'GENERAL LAS HERAS',
  'CORBETA PI Y MARGAL',
  'CERVIÃ‘O',
  'DIAZ VELEZ',
  'DOCTOR JUAN FELIPE ARANGUREN',
  'GENERAL URQUIZA',
  'MONROE',
  'NUEVA YORK',
  'PEDRO CALDERON DE LA BARCA',
  'PILAR',
  'PEDRO CHUTRO',
  'COMBATIENTES DE MALVINAS',
  'VARELA',
  '"FERNANDEZ DE LA CRUZ',
  'COMBATE DE LOS POZOS',
  'SUAREZ'],
 'ALTURA': ['"40"',
  '"1330"',
  '"2529"',
  '"2570"',
  '"2061"',
  '"4821"',
  '"849"',
  '"315"',
  '"375"',
  '"1795"',
  '"955"',
  '"2151"',
  '"4151"',
  '"15"',
  '"150"',
  '"369"',
  '"2021"',
  '"1949"',
  '"2272"',
  '"2630"',
  '"2670"',
  '"750"',
  '"3356"',
  '"5044"',
  '"2701"',
  '"609"',
  '"3555"',
  '"3952"',
  '"1550"',
  '"950"',
  '"3380"',
  '"3002"',
  '"1301"',
  ' F.',
  '"1881"',
  '"2215"'],
 'DOM_NORMA': ['"MONTES DE OCA',
  'GALLO 1330',
  'SANCHEZ DE BUSTAMANTE 2529',
  'BRANDSEN 2570',
  'CASEROS AV. 2061',
  'DIAZ VELEZ AV. 4821',
  'FINOCHIETTO ENRIQUE DR. 849',
  '"CARRILLO',
  '"CARRILLO',
  'DON PEDRO DE MENDOZA AV. 1795',
  'ECHEVERRIA 955',
  '"LUCA',
  '"JUSTO',
  'MUÃ‘IZ 15',
  'PATRICIAS ARGENTINAS AV. 150',
  '"GOYENA',
  'SAN JUAN AV. 2021',
  'SEGUROLA AV. 1949',
  'USPALLATA 2272',
  'WARNES AV. 2630',
  'LAS HERAS GENERAL AV. 2670',
  'PI Y MARGALL 750',
  'CERVIÃ‘O AV. 3356',
  'DIAZ VELEZ AV. 5044',
  '"ARANGUREN',
  '"URQUIZA',
  'MONROE AV. 3555',
  'NUEVA YORK 3952',
  '"CALDERON DE LA BARCA',
  'PILAR 950',
  '"CHUTRO',
  'COMBATIENTES DE MALVINAS AV. 3002',
  'VARELA AV. 1301',
  ' GRAL. AV. 4402"',
  'COMBATE DE LOS POZOS 1881',
  'SUAREZ AV. 2215'],
 'DOM_GEO': [' MANUEL AV. 40"',
  '1330 GALLO',
  '2529 SANCHEZ DE BUSTAMANTE',
  '2570 BRANDSEN',
  '2061 CASEROS AV.',
  '4821 DIAZ VELEZ AV.',
  '849 FINOCHIETTO ENRIQUE DR.',
  ' RAMON',
  ' RAMON',
  '1795 DON PEDRO DE MENDOZA AV.',
  '955 ECHEVERRIA',
  ' ESTEBAN DE 2151"',
  ' JUAN B. AV. 4151"',
  '15 MUÃ‘IZ',
  '150  PATRICIAS ARGENTINAS AV.',
  ' PEDRO AV. 369"',
  '2021 SAN JUAN AV.',
  '1949 SEGUROLA AV.',
  '2272 USPALLATA',
  '2630 WARNES AV.',
  '2670 LAS HERAS GENERAL AV.',
  '750 PI Y MARGALL',
  '3356 CERVIÃ‘O AV.',
  '5044 DIAZ VELEZ AV.',
  ' JUAN F.',
  ' GRAL. 609"',
  '3555 MONROE AV.',
  '3952 NUEVA YORK',
  ' PEDRO 1550"',
  '950 PILAR',
  ' PEDRO',
  '3002 COMBATIENTES DE MALVINAS AV.',
  '1301 VARELA AV.',
  '"4402"',
  '1881 COMBATE DE LOS POZOS',
  '2215 SUAREZ AV.'],
 'TELEFONO': ['"40 MONTES DE OCA',
  '4962-9247 / 9248 / 9280',
  '4805-5521 / 7533',
  '4301-3655 / 3659',
  '4306-4641 al 4649',
  '4958-9900',
  '4307-1445 / 4677 / 6777 / 6738 / 7474',
  ' DR. 315"',
  ' DR. 375"',
  '4360- 3900 / 4301-4870 / 4834 / 4302-9492 / 9510',
  '4781-6071 al 74',
  '"2151 LUCA',
  '"4151 JUSTO',
  '4983-0392 / 4983-8983',
  '4982-1731 / 1831',
  '"369 GOYENA',
  '4127-3100 / 4941-5555',
  '4630-4700 / 4800',
  '4304-2180 / 3380 / 4306-7855',
  '4521-0273 / 0090 / 0983',
  '4809-2000',
  '4121-0700 / 0800',
  '4808-2600',
  '4982-5555 / 4982-5655 Conmutador 4982-1050 / 4981-2670',
  ' DR. 2701"',
  '"609 URQUIZA',
  '4123-3100',
  '4501-5985 / 0683',
  '"1550 CALDERON DE LA BARCA',
  '4630-5500 / 5509',
  ' PROF.',
  '4521-3600 / 1236 / 8700',
  '4631-8100 / 0526',
  '"FERNANDEZ DE LA CRUZ',
  '"4941-8772 / 4942-7475',
  '4301-3961'],
 'GUARDIA': [' MANUEL AV."',
  '4962-9232',
  '4805-6407',
  '4301-4522',
  '4306-4641 al 49 (int. 125)',
  '4982-8421 / 4504 / 6666',
  '4307-1445 (int. 145)',
  '"315 CARRILLO',
  '"375 CARRILLO',
  '4301-4870',
  '4784-1225',
  ' ESTEBAN DE"',
  ' JUAN B. AV."',
  '4983-0392 / 4983-8983',
  '4982-1731 / 1831 / 5744',
  ' PEDRO AV."',
  '4941- 8081',
  '4630-4741 / 4742',
  '4304-5555 / 4304-3380 / 2946 (int. 213)',
  '4521-5555 / 5934',
  '4809-2002 / 2340',
  '4121-0683',
  '4808-5555 / 2600 / 2650 / 2640',
  '4982-1771 / 4982-5555 / 4981-2790',
  '"2701 ARANGUREN',
  ' GRAL."',
  '4542-5552 / 2772 / 9279',
  '4501-5555 / 0683 / 5985',
  ' PEDRO"',
  '4630-5673 / 5606 / 5536',
  ' DR. 3380"',
  '4521-6666',
  '4631-8601',
  ' F.',
  ''],
 'FAX': ['4307-5842 / 5844',
  '4962-3762',
  '4805-7533',
  '4303-3655/59',
  '4306-3013',
  '4983-7300',
  '4307-2567',
  ' RAMON',
  ' RAMON',
  '4301-4870',
  '478-30398',
  '4943-3567',
  '4582-1278 / 4581-7766 / 0645',
  '4983-0688',
  '4982-3972',
  '4923-3022',
  '4941-7077',
  '4566-4206',
  '4304-2386',
  '4521-2537',
  '4802-2721',
  '4362-2621',
  '4801-0932',
  '4982-2677',
  ' JUAN F.',
  '4127-0200 / 300',
  '4543-2199',
  '4501-2604',
  '4639-8700 al 05',
  '4641-3359',
  '"3380 CHUTRO',
  '4521-6677',
  '4632-8626',
  ' GRAL. 4402"',
  '4302-9160'],
 'WEB': ['4307-5442 / 4300-1700',
  'www.guti.gov.ar',
  '',
  'www.moyano.org.ar',
  '',
  '',
  '',
  ' DR."',
  ' DR."',
  '',
  '',
  '4943-4250',
  '4581-0645 / 7766 / 2792  4582-8235 / 1278 (int. 108)',
  '',
  '',
  '4923-4082 / 4923-3022',
  'www.hospitalsantalucia.com.ar',
  '',
  '',
  '',
  'www.buenosaires.gov.ar/areas/salud/rivadavia',
  '',
  '',
  'www.hospitaldurand.org.ar',
  ' DR."',
  '4127-0400',
  '',
  'www.zubizarreta.org.ar',
  '4639-8700 (int. 342)',
  'www.hospitalsantojanni.gov.ar',
  ' PEDRO',
  '',
  '',
  '"4402 FERNANDEZ DE LA CRUZ',
  ''],
 'COD_POSTAL': ['4302-7400',
  'C1425EFD',
  'C1425DUY',
  'C1287ABJ',
  'C1264AAA',
  'C1405DCD',
  'C1272AAA',
  '4305-6108',
  '4305-6485',
  'C1169AAB',
  'C1428DQG',
  '494-34966',
  '4582-1278',
  'C1212AAA',
  'C1405BWU',
  '4925-3557',
  'C1232AAC',
  'C1407AOM',
  'C1282AEN',
  'C1427DPS',
  'C1425ASQ',
  'C1155AHD',
  'C1425AGP',
  'C1405DCS',
  '4611-6666 / 4630-2900',
  '4932-8858',
  'C1430BKC',
  'C1419HDN',
  '4566-9590',
  'C1408INH',
  ' PROF.',
  'C1427ARN',
  'C1406ELA',
  ' F.',
  'C1284AGA'],
 'TIPO': ['www.elizalde.gov.ar',
  'Hospital de niÃ±os',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  '4304-6666',
  '4305-6666 / 6485',
  'Hospital especializado',
  'Hospital especializado',
  'www.sarda.org.ar',
  '',
  'Hospital especializado',
  'Hospital especializado',
  'www.buenosaires.gov.ar/areas/salud/hospital_quemados/?menu_id=24263',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital de agudos',
  'Hospital de agudos',
  'Hospital de agudos',
  'Hospital de agudos',
  '4611-6666 (int. 2111 y 2948)',
  'www.hospitalramosmejia.info',
  'Hospital de agudos',
  'Hospital de agudos',
  'www.hospitalvelez.org.ar',
  'Hospital de agudos',
  ' DR."',
  'Hospital de agudos',
  'Hospital de agudos',
  ' GRAL."',
  'Hospital especializado'],
 'TIPO_ESPEC': ['C1270AAN',
  'PEDIATRIA',
  'ODONTOLOGIA',
  'SALUD MENTAL',
  'ENF. APAR. DIGESTIVO',
  'ZOONOSIS',
  'NEUMONOLOGIA',
  '4304-4911',
  '4304-1200',
  'ODONTOLOGIA',
  'MED. FISICA/REHABILITACION',
  'C1246ABQ',
  'C1416DJI',
  'ODONTOLOGIA',
  'ONCOLOGIA',
  'C1424BSD',
  'OFTALMOLOGIA',
  'MED. FISICA/REHABILITACION',
  'INFECTOLOGIA',
  'SALUD MENTAL',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  '4612-5073',
  'C1221ADC',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  'C1407KQF',
  'GRAL: BAS/CRIT/OTR',
  '4912-1085',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  '4604-9000',
  'SALUD MENTAL'],
 'MOD_AT_1': ['Hospital de niÃ±os',
  'AT. AMB./INTERNACION',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  '',
  '',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  'Hospital especializado',
  'Hospital especializado',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  'Hospital especializado',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  '',
  'Hospital de agudos',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'Hospital de agudos',
  'AT. AMB./INTERNACION',
  '4911-5555 / 3030 (int. 230/268)',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  '',
  'AT. AMBULATORIA'],
 'MOD_AT_2': ['PEDIATRIA',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'C1275AHG',
  'C1275AHG',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'MATERNO-INFANTIL',
  'OFTALMOLOGIA',
  'DIAGNOSTICO',
  'DIAG./TRATAM.',
  'QUEMADOS',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAGNOSTICO',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'C1406FWY',
  'GRAL: BAS/CRIT/OTR',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'GRAL: BAS/CRIT/OTR',
  'DIAG./TRATAM.',
  '4911-7222',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  '',
  'DIAGNOSTICO'],
 'DEPEND_ADM': ['AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Hospital especializado',
  'Hospital especializado',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Hospital de agudos',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  '',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  '',
  'Ministerio de Salud GCBA'],
 'DIRECTOR': ['DIAG./TRATAM.',
  'Dra. MarÃ\xada Cristina Galoppo',
  'Dra. Susana Rita Lisanti',
  'Dra. Norma Derito',
  'Dr. Eduardo Gustavo Sosa',
  'Dr. Oscar Enrique Lencinas',
  'Dra. Dora Lombardi',
  'SALUD MENTAL',
  'SALUD MENTAL',
  'Dra. Scagnet Gabriela',
  'Dra. Silvina Ajolfi',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'Dra. Ada Severino',
  'Dr. Alejandro FernÃ¡ndez',
  'DIAG./TRATAM.',
  'Dra. Estela FernÃ¡ndez Rey',
  'Dr. Cichero Carlos',
  'Dr. GonzÃ¡lez Montaner Pablo',
  'Dr. Marcelo Ernesto Lahitou',
  'Dr. Eduardo FernÃ¡ndez Rostello',
  'Dr. NÃ©stor HernÃ¡ndez',
  'Dr. Previgliano Ignacio',
  'Dr. Bolla Horacio Alberto',
  'GRAL: BAS/CRIT/OTR',
  'DIAG./TRATAM.',
  'Dr. JosÃ© Antonio Cuba',
  'Dra. Lilia Borelli',
  'DIAG./TRATAM.',
  'Dr. Federico Charabora',
  'C1437JLR',
  'Dr. Luis Eduardo CastaÃ±iza',
  'Dr. Rivero Marino Daniel',
  'C1439CNU',
  'Dra. Graciela MarÃ\xada Ana Russo']}

In [ ]:
'''Ahora deberíamos separar esas coordenadas en dos columnas distintas. Latitud y Longitud.
Pero en inglés, tal como lo pide el ejercicio.
'''
LATITUDE = []
LONGITUDE = []
for index, elemento in enumerate(dicc['WKT']):
    elemento = elemento.split(' ')
    LATITUDE.append(elemento[0])
    LONGITUDE.append(elemento[1])
print(LATITUDE)
print(LONGITUDE)

['-58.3775508488443', '-58.4120700769456', '-58.4027276547828', '-58.3851559118889', '-58.3913114406535', '-58.4349433479819', '-58.3758433488021', '-58.3823284509488', '-58.3821283746958', '-58.3601201271455', '-58.4409882382439', '-58.4027506275377', '-58.4601855775528', '-58.4276597542837', '-58.4332484381295', '-58.4323966950244', '-58.3940641604746', '-58.5021449222222', '-58.3937269413225', '-58.4752588459761', '-58.4005134574423', '-58.365985088719', '-58.4068939142787', '-58.437981361705', '-58.4695020363265', '-58.4096107488155', '-58.4710781593251', '-58.5110525000569', '-58.50761514092', '-58.5156291936709', '-58.4108602188291', '-58.4710976282168', '-58.4541167814714', '-58.4566428491103', '-58.3918791813882', '-58.3814293381891']
['-34.6288473603881', '-34.5941919726393', '-34.5845283357505', '-34.6394041316484', '-34.6341535760002', '-34.6084721257413', '-34.6302112044495', '-34.6357022351559', '-34.6364350546569', '-34.6388917320834', '-34.5538963316473', '-34.634856308415', '-34.6054342750207', '-34.6146348348429', '-34.6070507603866', '-34.6255031952483', '-34.6227125075124', '-34.6179817540591', '-34.6375293258416', '-34.5972098729151', '-34.5847659581214', '-34.6283448581677', '-34.581141710889', '-34.6089728538414', '-34.6241704940114', '-34.6176598438607', '-34.565051956568', '-34.599979524264', '-34.6253367952668', '-34.6491867281064', '-34.6431172591975', '-34.5873917690227', '-34.643894071866', '-34.6718480140772', '-34.6299453614404', '-34.6419888014928']

In [ ]:
'''Agregamos la nueva columna al diccionario latitud y longitud'''
dicc['LATITUDE'] = LATITUDE
dicc['LONGITUDE'] = LONGITUDE

In [ ]:
'''Ahora deberíamos borrar la primera columna y reordenar el diccionario
Así de fácil es: 😎'''
del dicc['WKT']

In [ ]:
'''Creamos la columna con el nombre de NAME, basicamente para cambiarle el
nombre a dom_norma'''
dicc['NAME']=dicc['DOM_NORMA']
#dicc['LATITUDE'],dicc['LONGITUDE']

In [ ]:
'''Luego borramos la columna dom_norma'''
del dicc['DOM_NORMA']

In [ ]:
'''Creamos la columna con el nombre label, que tenga el nombre del hospital'''
dicc['LABEL'] = dicc['NOMBRE']

In [ ]:
'''Luego borramos la columna con el nombre del hospital'''
del dicc['NOMBRE']

In [ ]:
dicc

{'ID': ['1.00000000000',
  '2.00000000000',
  '4.00000000000',
  '6.00000000000',
  '7.00000000000',
  '8.00000000000',
  '9.00000000000',
  '10.00000000000',
  '11.00000000000',
  '12.00000000000',
  '13.00000000000',
  '14.00000000000',
  '15.00000000000',
  '16.00000000000',
  '17.00000000000',
  '18.00000000000',
  '19.00000000000',
  '20.00000000000',
  '21.00000000000',
  '22.00000000000',
  '23.00000000000',
  '24.00000000000',
  '25.00000000000',
  '26.00000000000',
  '27.00000000000',
  '28.00000000000',
  '29.00000000000',
  '30.00000000000',
  '31.00000000000',
  '32.00000000000',
  '33.00000000000',
  '34.00000000000',
  '35.00000000000',
  '36.00000000000',
  '3.00000000000',
  '5.00000000000'],
 'NOM_MAP': ['HOSP. DE ELIZALDE',
  'HOSP. GUTIERREZ',
  'HOSP. ODONTOLOGICO CARRILLO',
  'HOSP. MOYANO',
  'HOSP. UDAONDO',
  'INST. PASTEUR',
  'HOSP. FERRER',
  'HOSP. TOBAR GARCIA',
  'HOSP. BORDA',
  'HOSP. ODONTOLOGICO INFANTIL QUINQUELA MARTIN',
  'INST. DE REHAB. PSICOFISICA',
  'HOSP. SARDA',
  'HOSP. LAGLEYZE',
  'HOSP. ODONTOLOGICO DUEÃ‘AS',
  'HOSP. CURIE',
  'HOSP. DE QUEMADOS A. U. ILLIA',
  'HOSP. SANTA LUCIA',
  'HOSP. DE REHAB. ROCCA',
  'HOSP. MUÃ‘IZ',
  'HOSP. T. DE ALVEAR',
  'HOSP. RIVADAVIA',
  'HOSP. ARGERICH',
  'HOSP. FERNANDEZ',
  'HOSP. DURAND',
  'HOSP. ALVAREZ',
  'HOSP. RAMOS MEJIA',
  'HOSP. PIROVANO',
  'HOSP. ZUBIZARRETA',
  'HOSP. VELEZ SARSFIELD',
  'HOSP. SANTOJANNI',
  'HOSP. PENNA',
  'HOSP. TORNU',
  'HOSP. PIÃ‘ERO',
  'HOSP. GRIERSON',
  'HOSP. GARRAHAN',
  'TALLERES DE REHAB. PSIQUIATRICA'],
 'OBJETO': ['HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL',
  'HOSPITAL'],
 'CALLE': ['MANUEL A. MONTES DE OCA',
  'GALLO',
  'SANCHEZ DE BUSTAMANTE',
  'BRANDSEN',
  'CASEROS',
  'DIAZ VELEZ',
  'DOCTOR ENRIQUE FINOCHIETTO',
  'DOCTOR RAMON CARRILLO',
  'DOCTOR RAMON CARRILLO',
  'DON PEDRO DE MENDOZA',
  'ECHEVERRIA',
  'ESTEBAN DE LUCA',
  'JUAN B. JUSTO',
  'MUÃ‘IZ',
  'PATRICIAS ARGENTINAS',
  'PEDRO GOYENA',
  'SAN JUAN',
  'SEGUROLA',
  'USPALLATA',
  'WARNES',
  'GENERAL LAS HERAS',
  'CORBETA PI Y MARGAL',
  'CERVIÃ‘O',
  'DIAZ VELEZ',
  'DOCTOR JUAN FELIPE ARANGUREN',
  'GENERAL URQUIZA',
  'MONROE',
  'NUEVA YORK',
  'PEDRO CALDERON DE LA BARCA',
  'PILAR',
  'PEDRO CHUTRO',
  'COMBATIENTES DE MALVINAS',
  'VARELA',
  '"FERNANDEZ DE LA CRUZ',
  'COMBATE DE LOS POZOS',
  'SUAREZ'],
 'ALTURA': ['"40"',
  '"1330"',
  '"2529"',
  '"2570"',
  '"2061"',
  '"4821"',
  '"849"',
  '"315"',
  '"375"',
  '"1795"',
  '"955"',
  '"2151"',
  '"4151"',
  '"15"',
  '"150"',
  '"369"',
  '"2021"',
  '"1949"',
  '"2272"',
  '"2630"',
  '"2670"',
  '"750"',
  '"3356"',
  '"5044"',
  '"2701"',
  '"609"',
  '"3555"',
  '"3952"',
  '"1550"',
  '"950"',
  '"3380"',
  '"3002"',
  '"1301"',
  ' F.',
  '"1881"',
  '"2215"'],
 'DOM_GEO': [' MANUEL AV. 40"',
  '1330 GALLO',
  '2529 SANCHEZ DE BUSTAMANTE',
  '2570 BRANDSEN',
  '2061 CASEROS AV.',
  '4821 DIAZ VELEZ AV.',
  '849 FINOCHIETTO ENRIQUE DR.',
  ' RAMON',
  ' RAMON',
  '1795 DON PEDRO DE MENDOZA AV.',
  '955 ECHEVERRIA',
  ' ESTEBAN DE 2151"',
  ' JUAN B. AV. 4151"',
  '15 MUÃ‘IZ',
  '150  PATRICIAS ARGENTINAS AV.',
  ' PEDRO AV. 369"',
  '2021 SAN JUAN AV.',
  '1949 SEGUROLA AV.',
  '2272 USPALLATA',
  '2630 WARNES AV.',
  '2670 LAS HERAS GENERAL AV.',
  '750 PI Y MARGALL',
  '3356 CERVIÃ‘O AV.',
  '5044 DIAZ VELEZ AV.',
  ' JUAN F.',
  ' GRAL. 609"',
  '3555 MONROE AV.',
  '3952 NUEVA YORK',
  ' PEDRO 1550"',
  '950 PILAR',
  ' PEDRO',
  '3002 COMBATIENTES DE MALVINAS AV.',
  '1301 VARELA AV.',
  '"4402"',
  '1881 COMBATE DE LOS POZOS',
  '2215 SUAREZ AV.'],
 'TELEFONO': ['"40 MONTES DE OCA',
  '4962-9247 / 9248 / 9280',
  '4805-5521 / 7533',
  '4301-3655 / 3659',
  '4306-4641 al 4649',
  '4958-9900',
  '4307-1445 / 4677 / 6777 / 6738 / 7474',
  ' DR. 315"',
  ' DR. 375"',
  '4360- 3900 / 4301-4870 / 4834 / 4302-9492 / 9510',
  '4781-6071 al 74',
  '"2151 LUCA',
  '"4151 JUSTO',
  '4983-0392 / 4983-8983',
  '4982-1731 / 1831',
  '"369 GOYENA',
  '4127-3100 / 4941-5555',
  '4630-4700 / 4800',
  '4304-2180 / 3380 / 4306-7855',
  '4521-0273 / 0090 / 0983',
  '4809-2000',
  '4121-0700 / 0800',
  '4808-2600',
  '4982-5555 / 4982-5655 Conmutador 4982-1050 / 4981-2670',
  ' DR. 2701"',
  '"609 URQUIZA',
  '4123-3100',
  '4501-5985 / 0683',
  '"1550 CALDERON DE LA BARCA',
  '4630-5500 / 5509',
  ' PROF.',
  '4521-3600 / 1236 / 8700',
  '4631-8100 / 0526',
  '"FERNANDEZ DE LA CRUZ',
  '"4941-8772 / 4942-7475',
  '4301-3961'],
 'GUARDIA': [' MANUEL AV."',
  '4962-9232',
  '4805-6407',
  '4301-4522',
  '4306-4641 al 49 (int. 125)',
  '4982-8421 / 4504 / 6666',
  '4307-1445 (int. 145)',
  '"315 CARRILLO',
  '"375 CARRILLO',
  '4301-4870',
  '4784-1225',
  ' ESTEBAN DE"',
  ' JUAN B. AV."',
  '4983-0392 / 4983-8983',
  '4982-1731 / 1831 / 5744',
  ' PEDRO AV."',
  '4941- 8081',
  '4630-4741 / 4742',
  '4304-5555 / 4304-3380 / 2946 (int. 213)',
  '4521-5555 / 5934',
  '4809-2002 / 2340',
  '4121-0683',
  '4808-5555 / 2600 / 2650 / 2640',
  '4982-1771 / 4982-5555 / 4981-2790',
  '"2701 ARANGUREN',
  ' GRAL."',
  '4542-5552 / 2772 / 9279',
  '4501-5555 / 0683 / 5985',
  ' PEDRO"',
  '4630-5673 / 5606 / 5536',
  ' DR. 3380"',
  '4521-6666',
  '4631-8601',
  ' F.',
  ''],
 'FAX': ['4307-5842 / 5844',
  '4962-3762',
  '4805-7533',
  '4303-3655/59',
  '4306-3013',
  '4983-7300',
  '4307-2567',
  ' RAMON',
  ' RAMON',
  '4301-4870',
  '478-30398',
  '4943-3567',
  '4582-1278 / 4581-7766 / 0645',
  '4983-0688',
  '4982-3972',
  '4923-3022',
  '4941-7077',
  '4566-4206',
  '4304-2386',
  '4521-2537',
  '4802-2721',
  '4362-2621',
  '4801-0932',
  '4982-2677',
  ' JUAN F.',
  '4127-0200 / 300',
  '4543-2199',
  '4501-2604',
  '4639-8700 al 05',
  '4641-3359',
  '"3380 CHUTRO',
  '4521-6677',
  '4632-8626',
  ' GRAL. 4402"',
  '4302-9160'],
 'WEB': ['4307-5442 / 4300-1700',
  'www.guti.gov.ar',
  '',
  'www.moyano.org.ar',
  '',
  '',
  '',
  ' DR."',
  ' DR."',
  '',
  '',
  '4943-4250',
  '4581-0645 / 7766 / 2792  4582-8235 / 1278 (int. 108)',
  '',
  '',
  '4923-4082 / 4923-3022',
  'www.hospitalsantalucia.com.ar',
  '',
  '',
  '',
  'www.buenosaires.gov.ar/areas/salud/rivadavia',
  '',
  '',
  'www.hospitaldurand.org.ar',
  ' DR."',
  '4127-0400',
  '',
  'www.zubizarreta.org.ar',
  '4639-8700 (int. 342)',
  'www.hospitalsantojanni.gov.ar',
  ' PEDRO',
  '',
  '',
  '"4402 FERNANDEZ DE LA CRUZ',
  ''],
 'COD_POSTAL': ['4302-7400',
  'C1425EFD',
  'C1425DUY',
  'C1287ABJ',
  'C1264AAA',
  'C1405DCD',
  'C1272AAA',
  '4305-6108',
  '4305-6485',
  'C1169AAB',
  'C1428DQG',
  '494-34966',
  '4582-1278',
  'C1212AAA',
  'C1405BWU',
  '4925-3557',
  'C1232AAC',
  'C1407AOM',
  'C1282AEN',
  'C1427DPS',
  'C1425ASQ',
  'C1155AHD',
  'C1425AGP',
  'C1405DCS',
  '4611-6666 / 4630-2900',
  '4932-8858',
  'C1430BKC',
  'C1419HDN',
  '4566-9590',
  'C1408INH',
  ' PROF.',
  'C1427ARN',
  'C1406ELA',
  ' F.',
  'C1284AGA'],
 'TIPO': ['www.elizalde.gov.ar',
  'Hospital de niÃ±os',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  '4304-6666',
  '4305-6666 / 6485',
  'Hospital especializado',
  'Hospital especializado',
  'www.sarda.org.ar',
  '',
  'Hospital especializado',
  'Hospital especializado',
  'www.buenosaires.gov.ar/areas/salud/hospital_quemados/?menu_id=24263',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital especializado',
  'Hospital de agudos',
  'Hospital de agudos',
  'Hospital de agudos',
  'Hospital de agudos',
  '4611-6666 (int. 2111 y 2948)',
  'www.hospitalramosmejia.info',
  'Hospital de agudos',
  'Hospital de agudos',
  'www.hospitalvelez.org.ar',
  'Hospital de agudos',
  ' DR."',
  'Hospital de agudos',
  'Hospital de agudos',
  ' GRAL."',
  'Hospital especializado'],
 'TIPO_ESPEC': ['C1270AAN',
  'PEDIATRIA',
  'ODONTOLOGIA',
  'SALUD MENTAL',
  'ENF. APAR. DIGESTIVO',
  'ZOONOSIS',
  'NEUMONOLOGIA',
  '4304-4911',
  '4304-1200',
  'ODONTOLOGIA',
  'MED. FISICA/REHABILITACION',
  'C1246ABQ',
  'C1416DJI',
  'ODONTOLOGIA',
  'ONCOLOGIA',
  'C1424BSD',
  'OFTALMOLOGIA',
  'MED. FISICA/REHABILITACION',
  'INFECTOLOGIA',
  'SALUD MENTAL',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  '4612-5073',
  'C1221ADC',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  'C1407KQF',
  'GRAL: BAS/CRIT/OTR',
  '4912-1085',
  'GRAL: BAS/CRIT/OTR',
  'GRAL: BAS/CRIT/OTR',
  '4604-9000',
  'SALUD MENTAL'],
 'MOD_AT_1': ['Hospital de niÃ±os',
  'AT. AMB./INTERNACION',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  '',
  '',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  'Hospital especializado',
  'Hospital especializado',
  'AT. AMBULATORIA',
  'AT. AMB./INTERNACION',
  'Hospital especializado',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  '',
  'Hospital de agudos',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'Hospital de agudos',
  'AT. AMB./INTERNACION',
  '4911-5555 / 3030 (int. 230/268)',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  '',
  'AT. AMBULATORIA'],
 'MOD_AT_2': ['PEDIATRIA',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'C1275AHG',
  'C1275AHG',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'MATERNO-INFANTIL',
  'OFTALMOLOGIA',
  'DIAGNOSTICO',
  'DIAG./TRATAM.',
  'QUEMADOS',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAGNOSTICO',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'C1406FWY',
  'GRAL: BAS/CRIT/OTR',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'GRAL: BAS/CRIT/OTR',
  'DIAG./TRATAM.',
  '4911-7222',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  '',
  'DIAGNOSTICO'],
 'DEPEND_ADM': ['AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Hospital especializado',
  'Hospital especializado',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'AT. AMB./INTERNACION',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'Hospital de agudos',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  'AT. AMB./INTERNACION',
  'Ministerio de Salud GCBA',
  '',
  'Ministerio de Salud GCBA',
  'Ministerio de Salud GCBA',
  '',
  'Ministerio de Salud GCBA'],
 'DIRECTOR': ['DIAG./TRATAM.',
  'Dra. MarÃ\xada Cristina Galoppo',
  'Dra. Susana Rita Lisanti',
  'Dra. Norma Derito',
  'Dr. Eduardo Gustavo Sosa',
  'Dr. Oscar Enrique Lencinas',
  'Dra. Dora Lombardi',
  'SALUD MENTAL',
  'SALUD MENTAL',
  'Dra. Scagnet Gabriela',
  'Dra. Silvina Ajolfi',
  'DIAG./TRATAM.',
  'DIAG./TRATAM.',
  'Dra. Ada Severino',
  'Dr. Alejandro FernÃ¡ndez',
  'DIAG./TRATAM.',
  'Dra. Estela FernÃ¡ndez Rey',
  'Dr. Cichero Carlos',
  'Dr. GonzÃ¡lez Montaner Pablo',
  'Dr. Marcelo Ernesto Lahitou',
  'Dr. Eduardo FernÃ¡ndez Rostello',
  'Dr. NÃ©stor HernÃ¡ndez',
  'Dr. Previgliano Ignacio',
  'Dr. Bolla Horacio Alberto',
  'GRAL: BAS/CRIT/OTR',
  'DIAG./TRATAM.',
  'Dr. JosÃ© Antonio Cuba',
  'Dra. Lilia Borelli',
  'DIAG./TRATAM.',
  'Dr. Federico Charabora',
  'C1437JLR',
  'Dr. Luis Eduardo CastaÃ±iza',
  'Dr. Rivero Marino Daniel',
  'C1439CNU',
  'Dra. Graciela MarÃ\xada Ana Russo'],
 'LATITUDE': ['-58.3775508488443',
  '-58.4120700769456',
  '-58.4027276547828',
  '-58.3851559118889',
  '-58.3913114406535',
  '-58.4349433479819',
  '-58.3758433488021',
  '-58.3823284509488',
  '-58.3821283746958',
  '-58.3601201271455',
  '-58.4409882382439',
  '-58.4027506275377',
  '-58.4601855775528',
  '-58.4276597542837',
  '-58.4332484381295',
  '-58.4323966950244',
  '-58.3940641604746',
  '-58.5021449222222',
  '-58.3937269413225',
  '-58.4752588459761',
  '-58.4005134574423',
  '-58.365985088719',
  '-58.4068939142787',
  '-58.437981361705',
  '-58.4695020363265',
  '-58.4096107488155',
  '-58.4710781593251',
  '-58.5110525000569',
  '-58.50761514092',
  '-58.5156291936709',
  '-58.4108602188291',
  '-58.4710976282168',
  '-58.4541167814714',
  '-58.4566428491103',
  '-58.3918791813882',
  '-58.3814293381891'],
 'LONGITUDE': ['-34.6288473603881',
  '-34.5941919726393',
  '-34.5845283357505',
  '-34.6394041316484',
  '-34.6341535760002',
  '-34.6084721257413',
  '-34.6302112044495',
  '-34.6357022351559',
  '-34.6364350546569',
  '-34.6388917320834',
  '-34.5538963316473',
  '-34.634856308415',
  '-34.6054342750207',
  '-34.6146348348429',
  '-34.6070507603866',
  '-34.6255031952483',
  '-34.6227125075124',
  '-34.6179817540591',
  '-34.6375293258416',
  '-34.5972098729151',
  '-34.5847659581214',
  '-34.6283448581677',
  '-34.581141710889',
  '-34.6089728538414',
  '-34.6241704940114',
  '-34.6176598438607',
  '-34.565051956568',
  '-34.599979524264',
  '-34.6253367952668',
  '-34.6491867281064',
  '-34.6431172591975',
  '-34.5873917690227',
  '-34.643894071866',
  '-34.6718480140772',
  '-34.6299453614404',
  '-34.6419888014928'],
 'NAME': ['"MONTES DE OCA',
  'GALLO 1330',
  'SANCHEZ DE BUSTAMANTE 2529',
  'BRANDSEN 2570',
  'CASEROS AV. 2061',
  'DIAZ VELEZ AV. 4821',
  'FINOCHIETTO ENRIQUE DR. 849',
  '"CARRILLO',
  '"CARRILLO',
  'DON PEDRO DE MENDOZA AV. 1795',
  'ECHEVERRIA 955',
  '"LUCA',
  '"JUSTO',
  'MUÃ‘IZ 15',
  'PATRICIAS ARGENTINAS AV. 150',
  '"GOYENA',
  'SAN JUAN AV. 2021',
  'SEGUROLA AV. 1949',
  'USPALLATA 2272',
  'WARNES AV. 2630',
  'LAS HERAS GENERAL AV. 2670',
  'PI Y MARGALL 750',
  'CERVIÃ‘O AV. 3356',
  'DIAZ VELEZ AV. 5044',
  '"ARANGUREN',
  '"URQUIZA',
  'MONROE AV. 3555',
  'NUEVA YORK 3952',
  '"CALDERON DE LA BARCA',
  'PILAR 950',
  '"CHUTRO',
  'COMBATIENTES DE MALVINAS AV. 3002',
  'VARELA AV. 1301',
  ' GRAL. AV. 4402"',
  'COMBATE DE LOS POZOS 1881',
  'SUAREZ AV. 2215'],
 'LABEL': ['HOSPITAL GENERAL DE NIÃ‘OS PEDRO DE ELIZALDE',
  'HOSPITAL GENERAL DE NIÃ‘OS RICARDO GUTIERREZ',
  'HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX NACIONAL)',
  'HOSPITAL DE SALUD MENTAL BRAULIO MOYANO',
  'HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO',
  'INSTITUTO DE ZOONOSIS L. PASTEUR',
  'HOSPITAL DE REHABILITACION RESPIRATORIA MARIA FERRER',
  'HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA',
  'HOSPITAL DE SALUD MENTAL J. T. BORDA',
  'HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QUINQUELA MARTIN',
  'INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E.P.)',
  'HOSPITAL MATERNO INFANTIL R. SARDA',
  'HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE',
  'HOSPITAL DE ODONTOLOGIA  JOSE DUEÃ‘AS',
  'HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE',
  'HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA',
  'HOSPITAL DE OFTALMOLOGIA SANTA LUCIA',
  'HOSPITAL DE REHABILITACION M. ROCCA',
  'HOSPITAL DE INFECCIOSAS F. MUÃ‘IZ',
  'HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO DE ALVEAR',
  'HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA',
  'HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH',
  'HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ',
  'HOSPITAL GENERAL DE AGUDOS DR. C. DURAND',
  'HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ',
  'HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA',
  'HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO',
  'HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA',
  'HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD',
  'HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI',
  'HOSPITAL GENERAL DE AGUDOS J. A. PENNA',
  'HOSPITAL GENERAL DE AGUDOS DR. E. TORNU',
  'HOSPITAL GENERAL DE AGUDOS P. PIÃ‘ERO',
  'HOSPITAL CECILIA GRIERSON',
  'HOSP. DE PEDIATRIA DR. J. GARRAHAN',
  'TALLERES PROTEGIDOS DE REHABILITACION PSIQUIATRICA']}

In [ ]:
dicc.keys()

dict_keys(['ID', 'NOM_MAP', 'OBJETO', 'CALLE', 'ALTURA', 'DOM_GEO', 'TELEFONO', 'GUARDIA', 'FAX', 'WEB', 'COD_POSTAL', 'TIPO', 'TIPO_ESPEC', 'MOD_AT_1', 'MOD_AT_2', 'DEPEND_ADM', 'DIRECTOR', 'LATITUDE', 'LONGITUDE', 'NAME', 'LABEL'])

In [ ]:
dicc_a_presentar = dicc.copy()

In [ ]:
del dicc_a_presentar['ID']
del dicc_a_presentar['NOM_MAP']
del dicc_a_presentar['OBJETO']
del dicc_a_presentar['CALLE']
del dicc_a_presentar['ALTURA']
del dicc_a_presentar['DOM_GEO']
del dicc_a_presentar['TELEFONO']
del dicc_a_presentar['GUARDIA']
del dicc_a_presentar['FAX']
del dicc_a_presentar['WEB']
del dicc_a_presentar['MOD_AT_1']
del dicc_a_presentar['MOD_AT_2']
del dicc_a_presentar['DEPEND_ADM']
del dicc_a_presentar['DIRECTOR']

In [ ]:
dicc_a_presentar.keys()

dict_keys(['COD_POSTAL', 'TIPO', 'TIPO_ESPEC', 'LATITUDE', 'LONGITUDE', 'NAME', 'LABEL'])

In [ ]:
'''Borramos las que faltaron'''
del dicc_a_presentar['COD_POSTAL']
del dicc_a_presentar['TIPO']
del dicc_a_presentar['TIPO_ESPEC']

### Diccionario Final:

Obtenemos el mismo resultado que en el dataframe, hecho con diccionarios 😎👌

In [ ]:
'''Diccionario Final:'''
dicc_a_presentar

{'LATITUDE': ['-58.3775508488443',
  '-58.4120700769456',
  '-58.4027276547828',
  '-58.3851559118889',
  '-58.3913114406535',
  '-58.4349433479819',
  '-58.3758433488021',
  '-58.3823284509488',
  '-58.3821283746958',
  '-58.3601201271455',
  '-58.4409882382439',
  '-58.4027506275377',
  '-58.4601855775528',
  '-58.4276597542837',
  '-58.4332484381295',
  '-58.4323966950244',
  '-58.3940641604746',
  '-58.5021449222222',
  '-58.3937269413225',
  '-58.4752588459761',
  '-58.4005134574423',
  '-58.365985088719',
  '-58.4068939142787',
  '-58.437981361705',
  '-58.4695020363265',
  '-58.4096107488155',
  '-58.4710781593251',
  '-58.5110525000569',
  '-58.50761514092',
  '-58.5156291936709',
  '-58.4108602188291',
  '-58.4710976282168',
  '-58.4541167814714',
  '-58.4566428491103',
  '-58.3918791813882',
  '-58.3814293381891'],
 'LONGITUDE': ['-34.6288473603881',
  '-34.5941919726393',
  '-34.5845283357505',
  '-34.6394041316484',
  '-34.6341535760002',
  '-34.6084721257413',
  '-34.6302112044495',
  '-34.6357022351559',
  '-34.6364350546569',
  '-34.6388917320834',
  '-34.5538963316473',
  '-34.634856308415',
  '-34.6054342750207',
  '-34.6146348348429',
  '-34.6070507603866',
  '-34.6255031952483',
  '-34.6227125075124',
  '-34.6179817540591',
  '-34.6375293258416',
  '-34.5972098729151',
  '-34.5847659581214',
  '-34.6283448581677',
  '-34.581141710889',
  '-34.6089728538414',
  '-34.6241704940114',
  '-34.6176598438607',
  '-34.565051956568',
  '-34.599979524264',
  '-34.6253367952668',
  '-34.6491867281064',
  '-34.6431172591975',
  '-34.5873917690227',
  '-34.643894071866',
  '-34.6718480140772',
  '-34.6299453614404',
  '-34.6419888014928'],
 'NAME': ['"MONTES DE OCA',
  'GALLO 1330',
  'SANCHEZ DE BUSTAMANTE 2529',
  'BRANDSEN 2570',
  'CASEROS AV. 2061',
  'DIAZ VELEZ AV. 4821',
  'FINOCHIETTO ENRIQUE DR. 849',
  '"CARRILLO',
  '"CARRILLO',
  'DON PEDRO DE MENDOZA AV. 1795',
  'ECHEVERRIA 955',
  '"LUCA',
  '"JUSTO',
  'MUÃ‘IZ 15',
  'PATRICIAS ARGENTINAS AV. 150',
  '"GOYENA',
  'SAN JUAN AV. 2021',
  'SEGUROLA AV. 1949',
  'USPALLATA 2272',
  'WARNES AV. 2630',
  'LAS HERAS GENERAL AV. 2670',
  'PI Y MARGALL 750',
  'CERVIÃ‘O AV. 3356',
  'DIAZ VELEZ AV. 5044',
  '"ARANGUREN',
  '"URQUIZA',
  'MONROE AV. 3555',
  'NUEVA YORK 3952',
  '"CALDERON DE LA BARCA',
  'PILAR 950',
  '"CHUTRO',
  'COMBATIENTES DE MALVINAS AV. 3002',
  'VARELA AV. 1301',
  ' GRAL. AV. 4402"',
  'COMBATE DE LOS POZOS 1881',
  'SUAREZ AV. 2215'],
 'LABEL': ['HOSPITAL GENERAL DE NIÃ‘OS PEDRO DE ELIZALDE',
  'HOSPITAL GENERAL DE NIÃ‘OS RICARDO GUTIERREZ',
  'HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX NACIONAL)',
  'HOSPITAL DE SALUD MENTAL BRAULIO MOYANO',
  'HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO',
  'INSTITUTO DE ZOONOSIS L. PASTEUR',
  'HOSPITAL DE REHABILITACION RESPIRATORIA MARIA FERRER',
  'HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA',
  'HOSPITAL DE SALUD MENTAL J. T. BORDA',
  'HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QUINQUELA MARTIN',
  'INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E.P.)',
  'HOSPITAL MATERNO INFANTIL R. SARDA',
  'HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE',
  'HOSPITAL DE ODONTOLOGIA  JOSE DUEÃ‘AS',
  'HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE',
  'HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA',
  'HOSPITAL DE OFTALMOLOGIA SANTA LUCIA',
  'HOSPITAL DE REHABILITACION M. ROCCA',
  'HOSPITAL DE INFECCIOSAS F. MUÃ‘IZ',
  'HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO DE ALVEAR',
  'HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA',
  'HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH',
  'HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ',
  'HOSPITAL GENERAL DE AGUDOS DR. C. DURAND',
  'HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ',
  'HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA',
  'HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO',
  'HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA',
  'HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD',
  'HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI',
  'HOSPITAL GENERAL DE AGUDOS J. A. PENNA',
  'HOSPITAL GENERAL DE AGUDOS DR. E. TORNU',
  'HOSPITAL GENERAL DE AGUDOS P. PIÃ‘ERO',
  'HOSPITAL CECILIA GRIERSON',
  'HOSP. DE PEDIATRIA DR. J. GARRAHAN',
  'TALLERES PROTEGIDOS DE REHABILITACION PSIQUIATRICA']}

In [ ]:
# load csv module
import csv

# define a dictionary with key value pairs
#dict = {'Python' : '.py', 'C++' : '.cpp', 'Java' : '.java'}

# open file for writing, "w" is writing
w = csv.writer(open("coordenadas.csv", "w"))

# loop over dictionary keys and values
for key, val in dicc_a_presentar.items():

    # write every key and value to file
    w.writerow([key, val])