In [ ]:
'''A partir del csv hospitales2.csv, generar un archivo CSV de salida,
que contenga los siguientes campos en este orden:
* latitude
* longitude
* name
* label
Con los correspondientes datos extraídos del CSV original, el campo name
tiene que corresponder con la dirección del hospital, y el campo label con
el nombre del hospital.'''

'A partir del csv hospitales2.csv, generar un archivo CSV de salida, \nque contenga los siguientes campos en este orden:\n* latitude\n* longitude\n* name\n* label\nCon los correspondientes datos extraídos del CSV original, el campo name\ntiene que corresponder con la dirección del hospital, y el campo label con\nel nombre del hospital.'

In [ ]:
import pandas as pd

,WKT,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,POINT (-58.3775508488443 -34.6288473603881),1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,POINT (-58.4120700769456 -34.5941919726393),2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo
2,POINT (-58.4027276547828 -34.5845283357505),4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,4805-6407,4805-7533,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti
3,POINT (-58.3851559118889 -34.6394041316484),6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,4301-4522,4303-3655/59,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito
4,POINT (-58.3913114406535 -34.6341535760002),7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,4306-4641 al 49 (int. 125),4306-3013,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa

` Un poco de ETL ó "Data Wrangling". Dejo el enlace de donde saqué la respuesta:
`

[Reemplazar valores de una columna en pandas](https://stackoverflow.com/questions/37593550/replace-method-not-working-on-pandas-dataframe)

In [ ]:
# Limpiar la columna WKT

`How to rename columns in pandas(with examples)`

[Como cambiar el nombre de las columnas en Pandas](https://www.statology.org/pandas-rename-columns/)

In [ ]:
# Renombrar la columna WKT

,Coordenadas,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,-58.3775508488443 -34.6288473603881,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,-58.4120700769456 -34.5941919726393,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo

In [ ]:
'''Primero acá me salía un error porque no me daba cuenta que en la columna "Coordenadas" hay un espacio
adelante de las coordenadas y un espacio entre medio, por lo que geométricamente,
por así decirlo, el script lo separa en 3 columnas. Y yo lo separaba en dos solamente.
Ahora miremos el error'''


'''Aparece el value error que dice que las columnas deben tener el mismo largo que la llave, osea que,
las columnas que estan siendo separadas'''

ValueError: Columns must be same length as key

In [ ]:
'''Acá tenemos la misma dimensión y luego funciona'''

### Atención !
----->
[De acá me robé el código anterior 😂👍](https://datascienceparichay.com/article/pandas-split-column-by-delimiter/#:~:text=Split%20column%20by%20delimiter%20into,True%20to%20the%20expand%20parameter.)<-----

In [ ]:
'''Volvemos a mostrar el dataframe y ahora lo que habría que hacer es eliminarle esa columna sin nada
y la columna de Coordenadas'''
df.head()

,Coordenadas,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,...,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR,,Latitude,Longitude
0,-58.3775508488443 -34.6288473603881,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,...,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart,,-58.3775508488443,-34.6288473603881
1,-58.4120700769456 -34.5941919726393,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,...,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo,,-58.4120700769456,-34.5941919726393
2,-58.4027276547828 -34.5845283357505,4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,...,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti,,-58.4027276547828,-34.5845283357505
3,-58.3851559118889 -34.6394041316484,6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,...,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito,,-58.3851559118889,-34.6394041316484
4,-58.3913114406535 -34.6341535760002,7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,...,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa,,-58.3913114406535,-34.6341535760002

In [ ]:
# Borrar lo innecesario

In [ ]:
'''Ahora vemos que el dataframe, pasó de 5 filas x 23 columnas a 5 filas x 21 columnas
   Borramos las columnas innecesarias.
   Me gustaría ordenar, sólo de caprichoso, el dataframe como estaba al inicio. La latitud y longitud al
   inicio del dataframe y no al final como está ahora.
'''
df.head()

,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,...,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR,Latitude,Longitude
0,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,...,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart,-58.3775508488443,-34.6288473603881
1,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,...,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo,-58.4120700769456,-34.5941919726393
2,4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,4805-6407,...,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti,-58.4027276547828,-34.5845283357505
3,6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,4301-4522,...,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito,-58.3851559118889,-34.6394041316484
4,7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,4306-4641 al 49 (int. 125),...,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa,-58.3913114406535,-34.6341535760002

[Como reordenar columnas?](https://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns)

`Primero ver la lista de columnas, cosa de que sea más fácil hacerlo manualmente. Luego copiar y pegarlas, y asignarle el orden deseado.`

In [ ]:
'''Así vemos las columnas en forma de lista: '''

['ID',
 'NOMBRE',
 'NOM_MAP',
 'OBJETO',
 'CALLE',
 'ALTURA',
 'DOM_NORMA',
 'DOM_GEO',
 'TELEFONO',
 'GUARDIA',
 'FAX',
 'WEB',
 'COD_POSTAL',
 'TIPO',
 'TIPO_ESPEC',
 'MOD_AT_1',
 'MOD_AT_2',
 'DEPEND_ADM',
 'DIRECTOR',
 'Latitude',
 'Longitude']

In [ ]:
'''Acá definimos el nuevo orden de las columnas'''

In [ ]:
'''Nuevo orden: '''

,Latitude,Longitude,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,...,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,-58.3775508488443,-34.6288473603881,1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",...,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,-58.4120700769456,-34.5941919726393,2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,...,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo
2,-58.4027276547828,-34.5845283357505,4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,...,4805-6407,4805-7533,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti
3,-58.3851559118889,-34.6394041316484,6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,...,4301-4522,4303-3655/59,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito
4,-58.3913114406535,-34.6341535760002,7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,...,4306-4641 al 49 (int. 125),4306-3013,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa

In [ ]:
# crear df de los pedidos

In [ ]:
# renombrar

C:\Users\Alfredo\anaconda3\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
# acotemos el dataframe

,Longitude,Latitude,Name,Label
0,-34.6288473603881,-58.3775508488443,"MONTES DE OCA, MANUEL AV. 40",HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE
1,-34.5941919726393,-58.4120700769456,GALLO 1330,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ
2,-34.5845283357505,-58.4027276547828,SANCHEZ DE BUSTAMANTE 2529,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...
3,-34.6394041316484,-58.3851559118889,BRANDSEN 2570,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO
4,-34.6341535760002,-58.3913114406535,CASEROS AV. 2061,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO
5,-34.6084721257413,-58.4349433479819,DIAZ VELEZ AV. 4821,INSTITUTO DE ZOONOSIS L. PASTEUR
6,-34.6302112044495,-58.3758433488021,FINOCHIETTO ENRIQUE DR. 849,HOSPITAL DE REHABILITACION RESPIRATORIA MARIA ...
7,-34.6357022351559,-58.3823284509488,"CARRILLO, RAMON, DR. 315",HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA
8,-34.6364350546569,-58.3821283746958,"CARRILLO, RAMON, DR. 375",HOSPITAL DE SALUD MENTAL J. T. BORDA
9,-34.6388917320834,-58.3601201271455,DON PEDRO DE MENDOZA AV. 1795,HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QU...
10,-34.5538963316473,-58.4409882382439,ECHEVERRIA 955,INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E...
11,-34.634856308415,-58.4027506275377,"LUCA, ESTEBAN DE 2151",HOSPITAL MATERNO INFANTIL R. SARDA
12,-34.6054342750207,-58.4601855775528,"JUSTO, JUAN B. AV. 4151",HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE
13,-34.6146348348429,-58.4276597542837,MUÑIZ 15,HOSPITAL DE ODONTOLOGIA JOSE DUEÑAS
14,-34.6070507603866,-58.4332484381295,PATRICIAS ARGENTINAS AV. 150,HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE
15,-34.6255031952483,-58.4323966950244,"GOYENA, PEDRO AV. 369",HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA
16,-34.6227125075124,-58.3940641604746,SAN JUAN AV. 2021,HOSPITAL DE OFTALMOLOGIA SANTA LUCIA
17,-34.6179817540591,-58.5021449222222,SEGUROLA AV. 1949,HOSPITAL DE REHABILITACION M. ROCCA
18,-34.6375293258416,-58.3937269413225,USPALLATA 2272,HOSPITAL DE INFECCIOSAS F. MUÑIZ
19,-34.5972098729151,-58.4752588459761,WARNES AV. 2630,HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO...
20,-34.5847659581214,-58.4005134574423,LAS HERAS GENERAL AV. 2670,HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA
21,-34.6283448581677,-58.365985088719,PI Y MARGALL 750,HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH
22,-34.581141710889,-58.4068939142787,CERVIÑO AV. 3356,HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ
23,-34.6089728538414,-58.437981361705,DIAZ VELEZ AV. 5044,HOSPITAL GENERAL DE AGUDOS DR. C. DURAND
24,-34.6241704940114,-58.4695020363265,"ARANGUREN, JUAN F., DR. 2701",HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ
25,-34.6176598438607,-58.4096107488155,"URQUIZA, GRAL. 609",HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA
26,-34.565051956568,-58.4710781593251,MONROE AV. 3555,HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO
27,-34.599979524264,-58.5110525000569,NUEVA YORK 3952,HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA
28,-34.6253367952668,-58.50761514092,"CALDERON DE LA BARCA, PEDRO 1550",HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD
29,-34.6491867281064,-58.5156291936709,PILAR 950,HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI
30,-34.6431172591975,-58.4108602188291,"CHUTRO, PEDRO, PROF., DR. 3380",HOSPITAL GENERAL DE AGUDOS J. A. PENNA
31,-34.5873917690227,-58.4710976282168,COMBATIENTES DE MALVINAS AV. 3002,HOSPITAL GENERAL DE AGUDOS DR. E. TORNU
32,-34.643894071866,-58.4541167814714,VARELA AV. 1301,HOSPITAL GENERAL DE AGUDOS P. PIÑERO
33,-34.6718480140772,-58.4566428491103,"FERNANDEZ DE LA CRUZ, F., GRAL. 4402",HOSPITAL CECILIA GRIERSON
34,-34.6299453614404,-58.3918791813882,COMBATE DE LOS POZOS 1881,HOSP. DE PEDIATRIA DR. J. GARRAHAN
35,-34.6419888014928,-58.3814293381891,SUAREZ AV. 2215,TALLERES PROTEGIDOS DE REHABILITACION PSIQUIAT...

In [ ]:
'''Les cambié el orden, porque cuando lo imprimia en https://www.gpsvisualizer.com/map?output_home
me tiraba las direcciones en el medio del oceano'''

Index(['Longitude', 'Latitude', 'Name', 'Label'], dtype='object')

In [ ]:
df_pedido

,Latitude,Longitude,Name,Label
0,-34.6288473603881,-58.3775508488443,"MONTES DE OCA, MANUEL AV. 40",HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE
1,-34.5941919726393,-58.4120700769456,GALLO 1330,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ
2,-34.5845283357505,-58.4027276547828,SANCHEZ DE BUSTAMANTE 2529,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...
3,-34.6394041316484,-58.3851559118889,BRANDSEN 2570,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO
4,-34.6341535760002,-58.3913114406535,CASEROS AV. 2061,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO
5,-34.6084721257413,-58.4349433479819,DIAZ VELEZ AV. 4821,INSTITUTO DE ZOONOSIS L. PASTEUR
6,-34.6302112044495,-58.3758433488021,FINOCHIETTO ENRIQUE DR. 849,HOSPITAL DE REHABILITACION RESPIRATORIA MARIA ...
7,-34.6357022351559,-58.3823284509488,"CARRILLO, RAMON, DR. 315",HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA
8,-34.6364350546569,-58.3821283746958,"CARRILLO, RAMON, DR. 375",HOSPITAL DE SALUD MENTAL J. T. BORDA
9,-34.6388917320834,-58.3601201271455,DON PEDRO DE MENDOZA AV. 1795,HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QU...
10,-34.5538963316473,-58.4409882382439,ECHEVERRIA 955,INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E...
11,-34.634856308415,-58.4027506275377,"LUCA, ESTEBAN DE 2151",HOSPITAL MATERNO INFANTIL R. SARDA
12,-34.6054342750207,-58.4601855775528,"JUSTO, JUAN B. AV. 4151",HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE
13,-34.6146348348429,-58.4276597542837,MUÑIZ 15,HOSPITAL DE ODONTOLOGIA JOSE DUEÑAS
14,-34.6070507603866,-58.4332484381295,PATRICIAS ARGENTINAS AV. 150,HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE
15,-34.6255031952483,-58.4323966950244,"GOYENA, PEDRO AV. 369",HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA
16,-34.6227125075124,-58.3940641604746,SAN JUAN AV. 2021,HOSPITAL DE OFTALMOLOGIA SANTA LUCIA
17,-34.6179817540591,-58.5021449222222,SEGUROLA AV. 1949,HOSPITAL DE REHABILITACION M. ROCCA
18,-34.6375293258416,-58.3937269413225,USPALLATA 2272,HOSPITAL DE INFECCIOSAS F. MUÑIZ
19,-34.5972098729151,-58.4752588459761,WARNES AV. 2630,HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO...
20,-34.5847659581214,-58.4005134574423,LAS HERAS GENERAL AV. 2670,HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA
21,-34.6283448581677,-58.365985088719,PI Y MARGALL 750,HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH
22,-34.581141710889,-58.4068939142787,CERVIÑO AV. 3356,HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ
23,-34.6089728538414,-58.437981361705,DIAZ VELEZ AV. 5044,HOSPITAL GENERAL DE AGUDOS DR. C. DURAND
24,-34.6241704940114,-58.4695020363265,"ARANGUREN, JUAN F., DR. 2701",HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ
25,-34.6176598438607,-58.4096107488155,"URQUIZA, GRAL. 609",HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA
26,-34.565051956568,-58.4710781593251,MONROE AV. 3555,HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO
27,-34.599979524264,-58.5110525000569,NUEVA YORK 3952,HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA
28,-34.6253367952668,-58.50761514092,"CALDERON DE LA BARCA, PEDRO 1550",HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD
29,-34.6491867281064,-58.5156291936709,PILAR 950,HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI
30,-34.6431172591975,-58.4108602188291,"CHUTRO, PEDRO, PROF., DR. 3380",HOSPITAL GENERAL DE AGUDOS J. A. PENNA
31,-34.5873917690227,-58.4710976282168,COMBATIENTES DE MALVINAS AV. 3002,HOSPITAL GENERAL DE AGUDOS DR. E. TORNU
32,-34.643894071866,-58.4541167814714,VARELA AV. 1301,HOSPITAL GENERAL DE AGUDOS P. PIÑERO
33,-34.6718480140772,-58.4566428491103,"FERNANDEZ DE LA CRUZ, F., GRAL. 4402",HOSPITAL CECILIA GRIERSON
34,-34.6299453614404,-58.3918791813882,COMBATE DE LOS POZOS 1881,HOSP. DE PEDIATRIA DR. J. GARRAHAN
35,-34.6419888014928,-58.3814293381891,SUAREZ AV. 2215,TALLERES PROTEGIDOS DE REHABILITACION PSIQUIAT...

str

<class 'numpy.float32'>
<class 'numpy.float32'>

In [ ]:
'''Es muy importante, poner el index = False. Porque si no se exporta con una coma y un indice adelante'''