# Pandas - Manipulación de datos

# Introducción a Pandas

Pandas es una poderosa herramienta de manipulación y análisis de datos en Python, desarrollada por [Wes McKinney](https://wesmckinney.com/). Inicialmente construida sobre Numpy y ahora compatible con tecnologías como Arrow, Pandas facilita la limpieza y transformación de datos en bruto, convirtiéndolos en formatos estructurados y aptos para el análisis.

Originalmente diseñada para gestionar datos financieros y ofrecer una alternativa a las hojas de cálculo tradicionales (como Microsoft Excel), se ha consolidado como una librería esencial para el procesamiento de datos y la estadística en Python.

## Tipos de Datos en Pandas

Pandas permite trabajar con distintos tipos de datos, entre los que destacan:

- **Datos tabulares:** Tablas con columnas heterogéneas y etiquetas tanto en filas como en columnas.
- **Series temporales:** Estructuras especializadas para el manejo de datos cronológicos.

## Funcionalidades Clave

Entre las principales funcionalidades de Pandas se incluyen:

- **Lectura y escritura de datos:** Soporta múltiples formatos, como CSV, JSON, Excel, bases de datos SQL, Parquet y HDF5, entre otros.
- **Selección y filtrado:** Permite extraer subconjuntos de datos basados en la posición, valores o etiquetas de forma sencilla.
- **Fusión y unión de datos:** Facilita la integración y combinación de diferentes conjuntos de datos.
- **Transformación de datos:** Ofrece herramientas para aplicar funciones tanto de forma global como a través de ventanas móviles.
- **Manipulación de series temporales:** Proporciona métodos especializados para el tratamiento y análisis de datos basados en el tiempo.
- **Visualización:** Incorpora funcionalidades para generar gráficos y explorar visualmente los datos.

## Estructuras de Datos Fundamentales

Pandas se basa en dos objetos principales:

- **Series:** Estructuras unidimensionales similares a listas.
- **DataFrame:** Estructuras bidimensionales que representan tablas de datos.

En resumen, Pandas ofrece las estructuras de datos y las funciones necesarias para transformar y analizar información de manera eficiente, consolidándose como una herramienta indispensable en el ecosistema Python para la ciencia de datos y la estadística.

In [3]:
import pandas as pd
import numpy as np
import sys

pd.__version__

'2.2.3'

# Series en Pandas

Una **Series** es uno de los tipos de datos fundamentales en Pandas. Es similar a un arreglo de NumPy, pero añade la ventaja de tener etiquetas en los ejes, lo que permite indexarla por etiquetas en lugar de usar únicamente posiciones numéricas. Además, una Series no se limita a contener datos numéricos; puede almacenar cualquier tipo de objeto de Python.

## Creación de una Series

Puedes crear una Series a partir de diferentes estructuras de datos (listas, arreglos de NumPy o diccionarios) utilizando el método `pd.Series`.

### Ejemplo: Preparación de Datos

In [2]:
# Definición de datos

labels = ["a", "b", "c"]          # Lista de etiquetas
my_list = [10, 20, 30]            # Lista de valores
arr = np.array([10, 20, 30])      # Arreglo de NumPy
d = {"a": 10, "b": 20, "c": 30}    # Diccionario

In [ ]:
# Tamaño en memoria

print(f"Lista 'labels': {sys.getsizeof(labels)} bytes")
print(f"Lista 'my_list': {sys.getsizeof(my_list)} bytes")
print(f"Array NumPy: {arr.nbytes} bytes (solo datos) + {sys.getsizeof(arr)} bytes (objeto completo)")
print(f"Diccionario: {sys.getsizeof(d)} bytes")

Lista 'labels': 88 bytes
Lista 'my_list': 88 bytes
Array NumPy: 24 bytes (solo datos) + 136 bytes (objeto completo)
Diccionario: 184 bytes

### Creación desde una lista

#### 1. Sin especificar etiquetas:

Al crear una Series a partir de una lista, se asignan automáticamente índices numéricos.

In [5]:
my_list

[10, 20, 30]

In [6]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

#### 2. Con etiquetas personalizadas:

Puedes especificar etiquetas usando el parámetro `index`.

In [8]:
labels

['a', 'b', 'c']

In [7]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

#### 3. Sintaxis abreviada

No es obligatorio usar el nombre del parámetro `data`.

In [9]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

#### 4. Creación desde un arreglo de NumPy

In [10]:
# con etiquetas

pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [11]:
# sin etiquetas

pd.Series(arr)

0    10
1    20
2    30
dtype: int64

#### 5. Creación desde un Diccionario

Al crear una Serie a partir de un diccionario, las claves se usan automáticamente como etiquetas.

In [12]:
d

{'a': 10, 'b': 20, 'c': 30}

In [13]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

#### 6. Serie con datos no numéricos

Una serie puede contener cualquier tipo de dato. Por ejemplo, crear una Series a partir de una lista de letras.

In [14]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

## Indexación y operaciones en una `Series`

El índice es fundamental en una Series, ya que permite acceder a los datos de manera rápida y eficiente, similar al funcionamiento de un diccionario.

In [17]:
# Creación de series

ser1 = pd.Series([1, 2, 3, 4], index=["USA", "Alemania", "Italia", "Japón"])
print(ser1)
print("-------------------------------------------------------------------------")
ser2 = pd.Series([1, 2, 5, 4], index=["USA", "Alemania", "Colombia", "Japón"])
print(ser2)

USA         1
Alemania    2
Italia      3
Japón       4
dtype: int64
-------------------------------------------------------------------------
USA         1
Alemania    2
Colombia    5
Japón       4
dtype: int64

In [19]:
# Acceso a elementos

print(ser1["USA"])

1

In [20]:
# Las operaciones también se realizan según el índice

ser1 + ser2

Alemania    4.0
Colombia    NaN
Italia      NaN
Japón       8.0
USA         2.0
dtype: float64

**Nótese que las etiquetas que no se encuentran en ambas resultan en `NaN`.**

# DataFrames

Los **DataFrames** son la estructura de datos más importante en Pandas y están directamente inspirados en el lenguaje de programación R. Se pueden entender como un conjunto de Series que comparten el mismo índice, lo que permite representar y manipular datos en forma de tabla de manera eficiente. Con un DataFrame, tienes la posibilidad de definir tanto los índices (nombres de las filas) como los nombres de las columnas, facilitando la organización y análisis de la información.

In [21]:
# Creación de un DataFrame

from numpy.random import randn

In [22]:
# Iniciar el generador aleatorio para obtener resultados reproducibles

np.random.seed(24)

In [25]:
# Forma rápida de crear una lista de python desde strings

filas = "A B C D E F".split()

filas

['A', 'B', 'C', 'D', 'E', 'F']

In [ ]:
# Crear una lista de etiquetas para las columnas

columnas = "W X Y Z".split()

In [27]:
# Crear un dataframe con números aleatorios de 4 columnas y 5 filas

df  =pd.DataFrame(randn(6, 4), filas, columnas)
df

          W         X         Y         Z
A  0.121668  1.207603 -0.002040  1.627796
B  0.354493  1.037528 -0.385684  0.519818
C  1.686583 -1.325963  1.428984 -2.089354
D -0.129820  0.631523 -0.586538  0.290720
E  1.264103  0.290035 -1.970288  0.803906
F  1.030550  0.118098 -0.021853  0.046841

## Explorando el DataFrame

Una vez creado el DataFrame, existen varias funciones útiles para obtener información general sobre su estructura y contenido.

In [28]:
# Número de filas y columnas

df.shape

(6, 4)

In [29]:
# Información general de los datos de cada columna

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, A to F
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       6 non-null      float64
 1   X       6 non-null      float64
 2   Y       6 non-null      float64
 3   Z       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0+ bytes

In [30]:
# Tipo de datos que existen en las columnas del dataframe

df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [31]:
# Estadística descriptiva de las columnas numéricas

df.describe()

              W         X         Y         Z
count  6.000000  6.000000  6.000000  6.000000
mean   0.721263  0.326470 -0.256237  0.199954
std    0.712819  0.911080  1.097574  1.247270
min   -0.129820 -1.325963 -1.970288 -2.089354
25%    0.179874  0.161082 -0.536324  0.107811
50%    0.692522  0.460779 -0.203768  0.405269
75%    1.205715  0.936026 -0.006993  0.732884
max    1.686583  1.207603  1.428984  1.627796

In [ ]:
df.head() # Primeras 5 filas

          W         X         Y         Z
A  0.121668  1.207603 -0.002040  1.627796
B  0.354493  1.037528 -0.385684  0.519818
C  1.686583 -1.325963  1.428984 -2.089354
D -0.129820  0.631523 -0.586538  0.290720
E  1.264103  0.290035 -1.970288  0.803906

In [33]:
df.tail() # Últimos 5 elementos

          W         X         Y         Z
B  0.354493  1.037528 -0.385684  0.519818
C  1.686583 -1.325963  1.428984 -2.089354
D -0.129820  0.631523 -0.586538  0.290720
E  1.264103  0.290035 -1.970288  0.803906
F  1.030550  0.118098 -0.021853  0.046841

In [34]:
df.sample(3) # Elementos aleatorios

          W         X         Y         Z
C  1.686583 -1.325963  1.428984 -2.089354
B  0.354493  1.037528 -0.385684  0.519818
F  1.030550  0.118098 -0.021853  0.046841

## Selección e indexación en DataFrames

Pandas ofrece diversos métodos para acceder y manipular los datos contenidos en un DataFrame. A continuación se muestran ejemplos prácticos de cómo seleccionar columnas, filas, crear nuevas columnas, eliminarlas y aplicar filtros condicionales.

In [35]:
# Acceso a columnas

df["W"]

A    0.121668
B    0.354493
C    1.686583
D   -0.129820
E    1.264103
F    1.030550
Name: W, dtype: float64

In [36]:
# Seleccionar dos o más columnas
# Se debe pasar una lista con los nombres de las columnas

df[["W", "Z"]]

          W         Z
A  0.121668  1.627796
B  0.354493  0.519818
C  1.686583 -2.089354
D -0.129820  0.290720
E  1.264103  0.803906
F  1.030550  0.046841