# POLARS - Manipulación de datos con Python

[Polars](https://pola.rs/) es una biblioteca de manipulación de datos de alto rendimiento desarrollada por [Ritchie Vink](https://www.linkedin.com/in/ritchievink/). Inicialmente, Polars fue diseñado para ofrecer una alternativa más rápida y eficiente a pandas, utilizando técnicas modernas de procesamiento paralelo y optimización de memoria. Polars está escrito en Rust, lo que le permite manejar grandes volúmenes de datos de manera eficiente y segura, aprovechando al máximo los recursos del hardware disponible.

Los principales tipos de datos que pueden representarse con Polars son:

* Datos tabulares con columnas de tipo heterogéneo con etiquetas en columnas y filas.
* Series temporales.

Polars proporciona herramientas que permiten:

* Leer y escribir datos en diferentes formatos: CSV, JSON, Parquet y más.
* Seleccionar y filtrar tablas de datos de manera sencilla en función de posición, valor o etiquetas.
* Fusionar y unir datos.
* Transformar datos aplicando funciones tanto globalmente como por ventanas.
* Manipulación de series temporales.
* Hacer gráficas.

En Polars existen 2 tipos básicos de objetos:

* Series (listas, 1D)
* DataFrame (tablas, 2D)

Polars nos proporciona las estructuras de datos y funciones necesarias para el análisis de datos de una manera eficiente y rápida, aprovechando las ventajas del procesamiento paralelo y la optimización de memoria. Esto hace que Polars sea una excelente opción para proyectos que requieren manejar grandes volúmenes de datos y realizar análisis complejos de manera eficiente.

<div class="alert alert-success">

<b>La filosofia de polars es en general:</b>

* Utilice todos los núcleos del procesador disponibles en tu máquina.
* Optimizar las consultas para reducir el trabajo innecesario y las asignaciones de memoria.
* Maneje datos mucho más grandes que la RAM disponible en la maquina.

</div>

Si consideras que ya sabes usar pandas, lo más recomendable es entender las diferencias entre Polars y Pandas. Para ello, se sugiere la siguiente lectura:

* https://docs.pola.rs/user-guide/migration/pandas/

## Diferencias principales entre Polars y Pandas

| **Aspecto**                 | **Pandas**                                                                                                                                                                                   | **Polars**                                                                                                                                                                                                           |
|-----------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Lenguaje subyacente**     | Construido originalmente sobre Python y NumPy (C en parte), pero la gestión de memoria puede verse limitada por la forma en la que Python maneja ciertos tipos de datos (por ejemplo, categóricos).                              | Escrito en Rust, lo que permite un control más eficiente de la memoria y un mejor aprovechamiento del hardware, similar a la velocidad de C o C++.                                                                    |
| **Rendimiento**             | Generalmente más lento cuando se trabaja con grandes volúmenes de datos o tipos de datos categóricos (pueden presentarse cuellos de botella en operaciones masivas).                                                              | Excelente rendimiento en operaciones intensivas gracias al paralelismo automático y la optimización interna, logrando procesar millones de filas de forma más veloz.                                                  |
| **Backend / Formato interno** | Pandas (hasta la versión 1.x) usaba principalmente estructuras basadas en NumPy. Con Pandas 2.0, adopta Arrow, pero usando la paquetería Pyarrow.                                                                                  | Utiliza Arrow como base, pero implementado directamente en Rust. Esto brinda gran interoperabilidad y estandarización de memoria, a la vez que mantiene un alto desempeño.                                            |
| **Evaluación**              | Evaluación inmediata (eager): cada operación se ejecuta al momento, lo que puede generar gastos computacionales repetidos (parciales) en la misma cadena de transformaciones.                                                     | Ofrece evaluación diferida (lazy), lo que acumula y optimiza las operaciones antes de ejecutarlas, reduciendo de manera significativa el tiempo total de procesamiento.                                               |
| **Uso de memoria**          | Puede ser más propenso a utilizar grandes cantidades de memoria en operaciones complejas y grandes volúmenes de datos.                                                                                                            | Maneja la memoria de forma más eficiente y optimizada, reduciendo la probabilidad de cuellos de botella y aprovechando mejor la RAM disponible.                                                                      |
| **Ecosistema y madurez**    | Amplio soporte y popularidad: muy integrado con librerías como scikit-learn, matplotlib, etc. Es la herramienta estándar para muchas tareas de análisis de datos en Python.                                                      | Cada vez más popular, en rápido desarrollo y con buena documentación. Ofrece integración creciente con otras librerías y se perfila como una alternativa robusta para el análisis de datos de alto rendimiento.         |

## Importando Polars

In [6]:
import polars as pl
import numpy as np

## Series

Una serie es el primer tipo de datos de Polars y es similar a una matriz NumPy. Lo que diferencia una matriz NumPy de una serie en Polars es que una serie puede tener etiquetas en los ejes, lo que significa que puede ser indexada por una etiqueta, en lugar de solo una ubicación numérica. Además, no necesita contener datos numéricos; puede contener cualquier objeto arbitrario compatible con Polars. Las series en Polars están diseñadas para ser eficientes y rápidas, aprovechando el rendimiento de Rust para manejar grandes volúmenes de datos de manera eficiente.

### Creando una Serie

Puede convertir una lista, una matriz numpy o un diccionario en una serie, usando el método pl.Series:

In [7]:
# Crear diferentes tipos de datos
labels = ['a','b','c'] # lista de etiquetas
my_list = [10,20,30] # lista con valores
arr = np.array([10,20,30]) # Convertir ista de valores en arreglo NumPy

In [8]:
# Convertir una lista en series usando el método pl.Series
# observe que se crean los nombres con las posiciones de cada elemento
pl.Series(values=my_list)

shape: (3,)
Series: '' [i64]
[
	10
	20
	30
]

In [9]:
# Convertir una lista en series usando el método pl.Series
# se puede ingresar el nombre de la serie
pl.Series(name= "numeros" ,values=my_list)

shape: (3,)
Series: 'numeros' [i64]
[
	10
	20
	30
]

In [10]:
import os

os.cpu_count()

2

In [11]:
# No es necesario ingresar la palabra de 'values =''  en el argumento
# Convertir una lista en series usando el método pl.Series
# se puede ingresar el nombre de la serie
pl.Series(my_list)

shape: (3,)
Series: '' [i64]
[
	10
	20
	30
]

In [12]:
# Desde Arreglos NumPy
# Convertir un arreglo en series usando el método pl.Series
pl.Series(arr)

shape: (3,)
Series: '' [i64]
[
	10
	20
	30
]

In [13]:
# Convertir un arreglo en series indicando también el nombre
pl.Series("numpy",arr)

shape: (3,)
Series: 'numpy' [i64]
[
	10
	20
	30
]

In [14]:
# Creando una serie basado solo en una lista de letras
pl.Series(values=labels)

shape: (3,)
Series: '' [str]
[
	"a"
	"b"
	"c"
]

### Indexación

Es diferente que pandas, Polars no utiliza un índice y cada fila se indexa por su posición entera en la tabla.

Veamos un ejemplo:

In [15]:
ser1 = pl.Series([1,2,3,4])

In [16]:
ser2 = pl.Series([1,2,5,4])

In [17]:
ser1[0]

1

In [18]:
ser1[3]

4

Las operaciones también se realizan según el índice:

In [19]:
ser1 + ser2

shape: (4,)
Series: '' [i64]
[
	2
	4
	8
	8
]

## DataFrames

Los DataFrames son la estructura mas importante en polars y están directamente inspirados en el lenguaje de programación R. Se puede pensar en un DataFrame como un conjunto de Series reunidas. En los DataFrame tenemos la opción de especificar tanto el columns (el nombre de las columnas).

In [20]:
# Importar la función de NumPy para crear arreglos de números enteros
from numpy.random import randn

np.random.seed(101) # Inicializar el generador aleatorio
# Crear un dataframe con números aleatorios de 4 Columnas y 5 Filas
# Esto evita tener que escribir repetidamente las comas

df = pl.DataFrame(
    {
        "W": randn(6),
        "X": randn(6),
        "Y": randn(6),
        "Z": randn(6)
    }
)
df

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

### Descripción general del DataFrame

In [21]:
# Número de filas y columnas

df.shape

(6, 4)

In [22]:
# Información general de los datos

df.collect_schema()

Schema([('W', Float64), ('X', Float64), ('Y', Float64), ('Z', Float64)])

In [23]:
# Solo ver los tipos de datos que existen en las columnas del dataframe

df.dtypes

[Float64, Float64, Float64, Float64]

### Resumen de estadística general

In [24]:
df.describe()

shape: (9, 5)
┌────────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ W         ┆ X         ┆ Y         ┆ Z         │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 6.0       ┆ 6.0       ┆ 6.0       ┆ 6.0       │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 0.84643   ┆ -0.263391 ┆ 0.270199  ┆ 0.403443  │
│ std        ┆ 1.002706  ┆ 1.087891  ┆ 1.087051  ┆ 1.642939  │
│ min        ┆ -0.319318 ┆ -2.018168 ┆ -0.933237 ┆ -1.706086 │
│ 25%        ┆ 0.503826  ┆ -0.848077 ┆ -0.758872 ┆ -1.159119 │
│ 50%        ┆ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ 0.683509  │
│ 75%        ┆ 0.907969  ┆ 0.605965  ┆ 0.955057  ┆ 1.693723  │
│ max        ┆ 2.70685   ┆ 0.740122  ┆ 1.978757  ┆ 2.605967  │
└────────────┴───────────┴───────────┴───────────┴───────────┘

In [25]:
# Ver primeros elementos del dataframe

df.head(3)

shape: (3, 4)
┌──────────┬───────────┬───────────┬──────────┐
│ W        ┆ X         ┆ Y         ┆ Z        │
│ ---      ┆ ---       ┆ ---       ┆ ---      │
│ f64      ┆ f64       ┆ f64       ┆ f64      │
╞══════════╪═══════════╪═══════════╪══════════╡
│ 2.70685  ┆ -0.848077 ┆ 0.188695  ┆ 2.605967 │
│ 0.628133 ┆ 0.605965  ┆ -0.758872 ┆ 0.683509 │
│ 0.907969 ┆ -2.018168 ┆ -0.933237 ┆ 0.302665 │
└──────────┴───────────┴───────────┴──────────┘

In [26]:
# Ver últimos elementos

df.tail(4)

shape: (4, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

In [27]:
# Ver elementos aleatorios

df.sample(3)

shape: (3, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

### Selección e Indexación

In [28]:
df["W"]

shape: (6,)
Series: 'W' [f64]
[
	2.70685
	0.628133
	0.907969
	0.503826
	0.651118
	-0.319318
]

In [29]:
df[['W', 'Z']]

shape: (6, 2)
┌───────────┬───────────┐
│ W         ┆ Z         │
│ ---       ┆ ---       │
│ f64       ┆ f64       │
╞═══════════╪═══════════╡
│ 2.70685   ┆ 2.605967  │
│ 0.628133  ┆ 0.683509  │
│ 0.907969  ┆ 0.302665  │
│ 0.503826  ┆ 1.693723  │
│ 0.651118  ┆ -1.706086 │
│ -0.319318 ┆ -1.159119 │
└───────────┴───────────┘

In [30]:
df[['X', 'W', 'Z']]

shape: (6, 3)
┌───────────┬───────────┬───────────┐
│ X         ┆ W         ┆ Z         │
│ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╡
│ -0.848077 ┆ 2.70685   ┆ 2.605967  │
│ 0.605965  ┆ 0.628133  ┆ 0.683509  │
│ -2.018168 ┆ 0.907969  ┆ 0.302665  │
│ 0.740122  ┆ 0.503826  ┆ 1.693723  │
│ 0.528813  ┆ 0.651118  ┆ -1.706086 │
│ -0.589001 ┆ -0.319318 ┆ -1.159119 │
└───────────┴───────────┴───────────┘

Las columnas de un dataframe son solo series

In [31]:
type(df['W'])

polars.series.series.Series

### Creación de nueva columna

Se realiza con el método `.with.columns()` y el nombre de la nueva columna se realiza con el método `.alias()`

In [32]:
# Nueva columnas igual a la suma de otras dos
# Operación vectorizada

df = df.with_columns((df["W"] + df["Y"]).alias("New W+Y"))

In [33]:
df

shape: (6, 5)
┌───────────┬───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         ┆ New W+Y   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  ┆ 2.895545  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  ┆ -0.130739 │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  ┆ -0.025268 │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  ┆ 1.458882  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 ┆ 0.841912  │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 ┆ 1.659439  │
└───────────┴───────────┴───────────┴───────────┴───────────┘

In [34]:
# Eliminando columnas

df.drop("New W+Y")

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

In [35]:
# Nótese que no se aplica al dataframe, a menos que se especifique

df

shape: (6, 5)
┌───────────┬───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         ┆ New W+Y   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  ┆ 2.895545  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  ┆ -0.130739 │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  ┆ -0.025268 │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  ┆ 1.458882  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 ┆ 0.841912  │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 ┆ 1.659439  │
└───────────┴───────────┴───────────┴───────────┴───────────┘

In [36]:
# Para que quede grabado, se debe asignar el resultado

df = df.drop('New W+Y')
df

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

### Obtener los nombres de las columnas y los indices (index)

#### Seleccionando Filas y Columnas

Las dos formas de selección principal son:

1. Usando `[]`
    * DataFrame[etiqueta_columna] <- por etiquetas de las columnas
    * DataFrame[indice_fila, indice_columna] <- por indices

2. Usando expresiones como `filter`, `select` and `with_columns`

    * Usa filter cuando necesites filtrar filas basadas en condiciones.
    * Usa select cuando necesites seleccionar y/o transformar columnas.
    * Usa with_columns cuando necesites añadir o modificar una o más columnas en el DataFrame. Puedes crear nuevas columnas o actualizar las existentes basándote en expresiones.

In [37]:
df['Z']

shape: (6,)
Series: 'Z' [f64]
[
	2.605967
	0.683509
	0.302665
	1.693723
	-1.706086
	-1.159119
]

In [38]:
df.head(1)

shape: (1, 4)
┌─────────┬───────────┬──────────┬──────────┐
│ W       ┆ X         ┆ Y        ┆ Z        │
│ ---     ┆ ---       ┆ ---      ┆ ---      │
│ f64     ┆ f64       ┆ f64      ┆ f64      │
╞═════════╪═══════════╪══════════╪══════════╡
│ 2.70685 ┆ -0.848077 ┆ 0.188695 ┆ 2.605967 │
└─────────┴───────────┴──────────┴──────────┘

In [39]:
# O basado en la posición en vez de usar la etiqueta

df[:,2]

shape: (6,)
Series: 'Y' [f64]
[
	0.188695
	-0.758872
	-0.933237
	0.955057
	0.190794
	1.978757
]

### Seleccionar un subconjunto de filas y columnas

In [40]:
# Mediante etiquetas
# Se selecciona el elemento que está en la fila=1 col=Y
df[1, 'Y']

-0.758872056210466

In [43]:
df

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

In [45]:
df.select(['W', 'Y'])

shape: (6, 2)
┌───────────┬───────────┐
│ W         ┆ Y         │
│ ---       ┆ ---       │
│ f64       ┆ f64       │
╞═══════════╪═══════════╡
│ 2.70685   ┆ 0.188695  │
│ 0.628133  ┆ -0.758872 │
│ 0.907969  ┆ -0.933237 │
│ 0.503826  ┆ 0.955057  │
│ 0.651118  ┆ 0.190794  │
│ -0.319318 ┆ 1.978757  │
└───────────┴───────────┘

### Selección Condicional o Filtros

Una característica importante de polars es la selección condicional usando el método `.filter()`.

Los términos de búsqueda condicional o filtros se entregan al método como tipo `string`

In [46]:
# Seleccionar todas las filas donde el valor que está en la columna "W" sea mayor que cero

df.filter(pl.col("W")>0) #

shape: (5, 4)
┌──────────┬───────────┬───────────┬───────────┐
│ W        ┆ X         ┆ Y         ┆ Z         │
│ ---      ┆ ---       ┆ ---       ┆ ---       │
│ f64      ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685  ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133 ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969 ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826 ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118 ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
└──────────┴───────────┴───────────┴───────────┘

Para dos condiciones, se usa los booleanos de esta forma

* | en vez de or
* & en vez de and
* ~ en vez de not

In [47]:
# Seleccionar las filas donde 'W' sea mayor que cero
# y también donde 'Y' sea mayor que 0.5

df.filter((pl.col('W') > 0) & (pl.col('Y') > 0.5))

shape: (1, 4)
┌──────────┬──────────┬──────────┬──────────┐
│ W        ┆ X        ┆ Y        ┆ Z        │
│ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╡
│ 0.503826 ┆ 0.740122 ┆ 0.955057 ┆ 1.693723 │
└──────────┴──────────┴──────────┴──────────┘

In [48]:
# Seleccionar las filas donde 'W' sea mayor que cero
# y de esas filas escoger los valores de la columna 'Y'

df.filter((pl.col('W') > 0))['Y']

shape: (5,)
Series: 'Y' [f64]
[
	0.188695
	-0.758872
	-0.933237
	0.955057
	0.190794
]

In [49]:
# Seleccionar las filas donde 'W' sea mayor que cero
# y de esas filas escoger los valores de las columna 'Y' y 'Z'

df.filter((pl.col('W') > 0))[['Y','Z']]

shape: (5, 2)
┌───────────┬───────────┐
│ Y         ┆ Z         │
│ ---       ┆ ---       │
│ f64       ┆ f64       │
╞═══════════╪═══════════╡
│ 0.188695  ┆ 2.605967  │
│ -0.758872 ┆ 0.683509  │
│ -0.933237 ┆ 0.302665  │
│ 0.955057  ┆ 1.693723  │
│ 0.190794  ┆ -1.706086 │
└───────────┴───────────┘

Para dos condiciones, puede usar `| = or` y `& = and` con paréntesis:

In [51]:
df

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

In [50]:
# Seleccionar las filas donde 'W' sea mayor que cero
# y también donde 'Y' sea mayor que 0.5

df.filter((pl.col('W') > 0) & (pl.col('Y') > 0.5))

shape: (1, 4)
┌──────────┬──────────┬──────────┬──────────┐
│ W        ┆ X        ┆ Y        ┆ Z        │
│ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╡
│ 0.503826 ┆ 0.740122 ┆ 0.955057 ┆ 1.693723 │
└──────────┴──────────┴──────────┴──────────┘

### Crear una Columna de Indexación

En Polars, a diferencia de Pandas, no existe el concepto de un índice nombrado para las filas, ya que las filas están indexadas de manera implícita con números enteros comenzando desde 0. Polars no tiene un índice explícito como Pandas, pero puedes lograr un efecto similar usando una columna adicional como índice.

Esta columna no tendrá ninguna propiedad especial.

In [52]:
# Crear columna indice con valores por defecto desde 0,1...n index
df = df.with_row_index()
df

shape: (6, 5)
┌───────┬───────────┬───────────┬───────────┬───────────┐
│ index ┆ W         ┆ X         ┆ Y         ┆ Z         │
│ ---   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ u32   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0     ┆ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 1     ┆ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 2     ┆ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 3     ┆ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 4     ┆ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ 5     ┆ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────┴───────────┴───────────┴───────────┴───────────┘

### Agrupación por Filas

El método groupby le permite agrupar filas de datos y llamar a funciones agregadas.

In [53]:
import polars as pl

# Crear dataframe desde un diccionario

data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB','GOOG','MSFT','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah','John','Randy','David'],
       'Sales':[200,120,340,124,243,350,275,400,180]}

data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB', 'GOOG', 'MSFT', 'FB'],
 'Person': ['Sam',
  'Charlie',
  'Amy',
  'Vanessa',
  'Carl',
  'Sarah',
  'John',
  'Randy',
  'David'],
 'Sales': [200, 120, 340, 124, 243, 350, 275, 400, 180]}

In [55]:
# Conversión del diccionario a dataframe

df = pl.DataFrame(data)
df

shape: (9, 3)
┌─────────┬─────────┬───────┐
│ Company ┆ Person  ┆ Sales │
│ ---     ┆ ---     ┆ ---   │
│ str     ┆ str     ┆ i64   │
╞═════════╪═════════╪═══════╡
│ GOOG    ┆ Sam     ┆ 200   │
│ GOOG    ┆ Charlie ┆ 120   │
│ MSFT    ┆ Amy     ┆ 340   │
│ MSFT    ┆ Vanessa ┆ 124   │
│ FB      ┆ Carl    ┆ 243   │
│ FB      ┆ Sarah   ┆ 350   │
│ GOOG    ┆ John    ┆ 275   │
│ MSFT    ┆ Randy   ┆ 400   │
│ FB      ┆ David   ┆ 180   │
└─────────┴─────────┴───────┘

Se puede usar el método `.groupby()` para agrupar filas en función de un nombre de columna. Por ejemplo, vamos a agruparnos a partir de la Compañía. Esto creará un objeto `polars.dataframe.group_by.GroupBy`:

In [56]:
#agrupar por Company

df.group_by('Company')

Se puede grabar este objeto en una nueva variable:

In [57]:
by_comp = df.group_by("Company")

In [61]:
by_comp

Utilizar los métodos agregados del objeto:

In [58]:
# Promedio de todas las columnas por company
by_comp.mean()

shape: (3, 3)
┌─────────┬────────┬────────────┐
│ Company ┆ Person ┆ Sales      │
│ ---     ┆ ---    ┆ ---        │
│ str     ┆ str    ┆ f64        │
╞═════════╪════════╪════════════╡
│ GOOG    ┆ null   ┆ 198.333333 │
│ MSFT    ┆ null   ┆ 288.0      │
│ FB      ┆ null   ┆ 257.666667 │
└─────────┴────────┴────────────┘

In [59]:
# Promedio de ventas por company, es bueno indicar las columnas numericas
# Para que tenga sentido
by_comp.mean()[["Company","Sales"]]

shape: (3, 2)
┌─────────┬────────────┐
│ Company ┆ Sales      │
│ ---     ┆ ---        │
│ str     ┆ f64        │
╞═════════╪════════════╡
│ GOOG    ┆ 198.333333 │
│ FB      ┆ 257.666667 │
│ MSFT    ┆ 288.0      │
└─────────┴────────────┘

In [ ]:
# agrupar por compañia y calcular el promedio por cada una

df.group_by('Company').mean()[["Company","Sales"]]

Más ejemplos con métodos agregados:

In [60]:
# agrupar por compañia y calcular la desviacion standard

by_comp.agg(pl.col('Sales').std())

shape: (3, 2)
┌─────────┬────────────┐
│ Company ┆ Sales      │
│ ---     ┆ ---        │
│ str     ┆ f64        │
╞═════════╪════════════╡
│ MSFT    ┆ 145.161978 │
│ FB      ┆ 85.94378   │
│ GOOG    ┆ 77.51344   │
└─────────┴────────────┘

In [62]:
# agrupar por compañia y calcular el minimo

by_comp.min()[["Company","Sales"]]

shape: (3, 2)
┌─────────┬───────┐
│ Company ┆ Sales │
│ ---     ┆ ---   │
│ str     ┆ i64   │
╞═════════╪═══════╡
│ FB      ┆ 180   │
│ GOOG    ┆ 120   │
│ MSFT    ┆ 124   │
└─────────┴───────┘

In [63]:
# agrupar por compañía y calcular el máximo

by_comp.max()[["Company","Sales"]]

shape: (3, 2)
┌─────────┬───────┐
│ Company ┆ Sales │
│ ---     ┆ ---   │
│ str     ┆ i64   │
╞═════════╪═══════╡
│ GOOG    ┆ 275   │
│ MSFT    ┆ 400   │
│ FB      ┆ 350   │
└─────────┴───────┘

In [64]:
# agrupar por compañía y sumar los elementos que hay excluyendo los NaN

by_comp.len()

shape: (3, 2)
┌─────────┬─────┐
│ Company ┆ len │
│ ---     ┆ --- │
│ str     ┆ u32 │
╞═════════╪═════╡
│ MSFT    ┆ 3   │
│ FB      ┆ 3   │
│ GOOG    ┆ 3   │
└─────────┴─────┘

In [65]:
# Para Generar estadísticas descriptivas que resuman la tendencia central,
# la dispersión y la forma de la distribución de un conjunto de datos,
# se pueden agrupar los calculos ccon el metodo .agg

by_comp.agg([
    pl.col("Sales").mean().alias("mean"),
    pl.col("Sales").std().alias("std"),
    pl.col("Sales").min().alias("min"),
    pl.col("Sales").max().alias("max"),
    pl.col("Sales").median().alias("median"),
    pl.col("Sales").count().alias("count")
])

shape: (3, 7)
┌─────────┬────────────┬────────────┬─────┬─────┬────────┬───────┐
│ Company ┆ mean       ┆ std        ┆ min ┆ max ┆ median ┆ count │
│ ---     ┆ ---        ┆ ---        ┆ --- ┆ --- ┆ ---    ┆ ---   │
│ str     ┆ f64        ┆ f64        ┆ i64 ┆ i64 ┆ f64    ┆ u32   │
╞═════════╪════════════╪════════════╪═════╪═════╪════════╪═══════╡
│ GOOG    ┆ 198.333333 ┆ 77.51344   ┆ 120 ┆ 275 ┆ 200.0  ┆ 3     │
│ MSFT    ┆ 288.0      ┆ 145.161978 ┆ 124 ┆ 400 ┆ 340.0  ┆ 3     │
│ FB      ┆ 257.666667 ┆ 85.94378   ┆ 180 ┆ 350 ┆ 243.0  ┆ 3     │
└─────────┴────────────┴────────────┴─────┴─────┴────────┴───────┘

## Pivot Tables

La funciónlidad “Pivot_table” es muy utilizada y popular en las conocidas “hojas de cálculo” tipo, OpenOffice, LibreOffice, Excel, Lotus, etc. Esta funcionalidad nos permite agrupar, ordenar, calcular datos y manejar datos de una forma muy similar a la que se hace con las hojas de cálculo. [Más información](https://docs.pola.rs/user-guide/transformations/pivot/).

La principal función del `.pivot` son las agrupaciones de datos a las que se les suelen aplicar funciones matemáticas como sumatorios, promedios, etc.

In [66]:
import seaborn as sns # importar la librería seaborn
# cargar dataset del titanic
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [67]:
type(titanic)

pandas.core.frame.DataFrame

In [68]:
# convertir dataframe de pandas a polars

titanic = pl.from_pandas(titanic)
type(titanic)

polars.dataframe.frame.DataFrame

In [69]:
# Haciendo el Pivot table a mano para obtener el promedio de personas que sobrevivieron por genero

# 1. Agrupar por genero
# 2. Obtener los sobrevivientes
# 3. Calcular el promedio

titanic.group_by('sex').mean()[["sex", "survived"]]

shape: (2, 2)
┌────────┬──────────┐
│ sex    ┆ survived │
│ ---    ┆ ---      │
│ str    ┆ f64      │
╞════════╪══════════╡
│ male   ┆ 0.188908 │
│ female ┆ 0.742038 │
└────────┴──────────┘

In [70]:
# Promedio de cuántos sobrevivieron por género divididos por clase

# 1. Agrupar por genero y clase
# 2. Calcular el promedio
# 3. Obtener los sobrevivientes

titanic.group_by(['sex', 'class']).mean()['sex', 'class','survived']

shape: (6, 3)
┌────────┬────────┬──────────┐
│ sex    ┆ class  ┆ survived │
│ ---    ┆ ---    ┆ ---      │
│ str    ┆ cat    ┆ f64      │
╞════════╪════════╪══════════╡
│ female ┆ Third  ┆ 0.5      │
│ male   ┆ Third  ┆ 0.135447 │
│ male   ┆ Second ┆ 0.157407 │
│ male   ┆ First  ┆ 0.368852 │
│ female ┆ Second ┆ 0.921053 │
│ female ┆ First  ┆ 0.968085 │
└────────┴────────┴──────────┘

**Usando Pivot Tables**

In [71]:
# Agrupar por 'sex' y 'class', calcular la media de 'survived' y hacer un pivot
grouped = titanic.group_by(['sex', 'class']).agg(
    pl.col('survived').mean()
)

# Crear una tabla dinámica (pivot table)
pivot_table = grouped.pivot(
    values='survived',
    index='sex',
    on='class'
)

pivot_table

shape: (2, 4)
┌────────┬──────────┬──────────┬──────────┐
│ sex    ┆ First    ┆ Second   ┆ Third    │
│ ---    ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ f64      ┆ f64      ┆ f64      │
╞════════╪══════════╪══════════╪══════════╡
│ female ┆ 0.968085 ┆ 0.921053 ┆ 0.5      │
│ male   ┆ 0.368852 ┆ 0.157407 ┆ 0.135447 │
└────────┴──────────┴──────────┴──────────┘

## Concatenar y Unir (Concatenating, Joining)

Hay dos formas principales de combinar DataFrames: concatenar y unir.

In [72]:
df1 = pl.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})
df2 = pl.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']})
df3 = pl.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']})

In [74]:
df1

shape: (4, 4)
┌─────┬─────┬─────┬─────┐
│ A   ┆ B   ┆ C   ┆ D   │
│ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str ┆ str │
╞═════╪═════╪═════╪═════╡
│ A0  ┆ B0  ┆ C0  ┆ D0  │
│ A1  ┆ B1  ┆ C1  ┆ D1  │
│ A2  ┆ B2  ┆ C2  ┆ D2  │
│ A3  ┆ B3  ┆ C3  ┆ D3  │
└─────┴─────┴─────┴─────┘

In [75]:
df2

shape: (4, 4)
┌─────┬─────┬─────┬─────┐
│ A   ┆ B   ┆ C   ┆ D   │
│ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str ┆ str │
╞═════╪═════╪═════╪═════╡
│ A4  ┆ B4  ┆ C4  ┆ D4  │
│ A5  ┆ B5  ┆ C5  ┆ D5  │
│ A6  ┆ B6  ┆ C6  ┆ D6  │
│ A7  ┆ B7  ┆ C7  ┆ D7  │
└─────┴─────┴─────┴─────┘

In [76]:
df3

shape: (4, 4)
┌─────┬─────┬─────┬─────┐
│ A   ┆ B   ┆ C   ┆ D   │
│ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str ┆ str │
╞═════╪═════╪═════╪═════╡
│ A8  ┆ B8  ┆ C8  ┆ D8  │
│ A9  ┆ B9  ┆ C9  ┆ D9  │
│ A10 ┆ B10 ┆ C10 ┆ D10 │
│ A11 ┆ B11 ┆ C11 ┆ D11 │
└─────┴─────┴─────┴─────┘

### Concatenación

La concatenación básicamente combina DataFrames. Tenga en cuenta que las dimensiones deben coincidir a lo largo del eje con el que se está concatenando.

la Concatenación se hace con dataframes de diferentes indices

Puede usar `.concat()` y pasar una lista de DataFrames para concatenar juntos:

In [73]:
# Concatenar cada dataframe verticalmente,
# ya que coinciden los nombres de las columnas

pl.concat([df1,df2,df3], how="vertical")

shape: (12, 4)
┌─────┬─────┬─────┬─────┐
│ A   ┆ B   ┆ C   ┆ D   │
│ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str ┆ str │
╞═════╪═════╪═════╪═════╡
│ A0  ┆ B0  ┆ C0  ┆ D0  │
│ A1  ┆ B1  ┆ C1  ┆ D1  │
│ A2  ┆ B2  ┆ C2  ┆ D2  │
│ A3  ┆ B3  ┆ C3  ┆ D3  │
│ A4  ┆ B4  ┆ C4  ┆ D4  │
│ …   ┆ …   ┆ …   ┆ …   │
│ A7  ┆ B7  ┆ C7  ┆ D7  │
│ A8  ┆ B8  ┆ C8  ┆ D8  │
│ A9  ┆ B9  ┆ C9  ┆ D9  │
│ A10 ┆ B10 ┆ C10 ┆ D10 │
│ A11 ┆ B11 ┆ C11 ┆ D11 │
└─────┴─────┴─────┴─────┘

**Los dataframes anteriores No se pueden concatenar Horizontalmente por que los dataframes tienen columnas con el mismo nombre**

In [78]:
df_h1 = pl.DataFrame({"l1": [1, 2], "l2": [3, 4]})
df_h2 = pl.DataFrame({"r1": [5, 6], "r2": [7, 8], "r3": [9, 10]})

In [79]:
df_h1

shape: (2, 2)
┌─────┬─────┐
│ l1  ┆ l2  │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘

In [80]:
df_h2

shape: (2, 3)
┌─────┬─────┬─────┐
│ r1  ┆ r2  ┆ r3  │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 5   ┆ 7   ┆ 9   │
│ 6   ┆ 8   ┆ 10  │
└─────┴─────┴─────┘

In [81]:
pl.concat([df_h1, df_h2], how="horizontal")

shape: (2, 5)
┌─────┬─────┬─────┬─────┬─────┐
│ l1  ┆ l2  ┆ r1  ┆ r2  ┆ r3  │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╪═════╡
│ 1   ┆ 3   ┆ 5   ┆ 7   ┆ 9   │
│ 2   ┆ 4   ┆ 6   ┆ 8   ┆ 10  │
└─────┴─────┴─────┴─────┴─────┘

In [85]:
pl.concat([df_h1, df_h2], how="vertical")

ShapeError: unable to append to a DataFrame of width 2 with a DataFrame of width 3

**Los `.join` funcionan exactamente igual que en pandas.**

## Datos Categóricos

La búsqueda en datos categoricos es mucho mas rápida.

* Ocupan Menos memoria que si los datos estan como string
* Se pueden tener datos categóricos ordinales
* Más información de datos categóricos:

    * https://docs.pola.rs/user-guide/concepts/data-types/categoricals/

### Creación

In [86]:
# Creacion de una serie de datos categoricos
cate = pl.Series(["manzana", "banano", "corozo", "manzana","pera"],
                 dtype=pl.Categorical)
cate

shape: (5,)
Series: '' [cat]
[
	"manzana"
	"banano"
	"corozo"
	"manzana"
	"pera"
]

In [88]:
cate.dtype

Categorical(ordering='physical')

In [89]:
cate.describe()

shape: (2, 2)
┌────────────┬───────┐
│ statistic  ┆ value │
│ ---        ┆ ---   │
│ str        ┆ str   │
╞════════════╪═══════╡
│ count      ┆ 5     │
│ null_count ┆ 0     │
└────────────┴───────┘

In [90]:
# Creando primero los datos y luego convirtiéndolos en categóricos

df_cate = pl.DataFrame({"Fruta":["manzana", "banano", "corozo", "manzana","pera"]})
df_cate

shape: (5, 1)
┌─────────┐
│ Fruta   │
│ ---     │
│ str     │
╞═════════╡
│ manzana │
│ banano  │
│ corozo  │
│ manzana │
│ pera    │
└─────────┘

In [91]:
# Observar los tipos de datos en el data frame

df_cate.dtypes

[String]

In [92]:
df_cate = df_cate.with_columns(
    pl.col("Fruta").cast(pl.Categorical).alias("Fruta2")
)
df_cate

shape: (5, 2)
┌─────────┬─────────┐
│ Fruta   ┆ Fruta2  │
│ ---     ┆ ---     │
│ str     ┆ cat     │
╞═════════╪═════════╡
│ manzana ┆ manzana │
│ banano  ┆ banano  │
│ corozo  ┆ corozo  │
│ manzana ┆ manzana │
│ pera    ┆ pera    │
└─────────┴─────────┘

In [93]:
# Observar los tipos de datos en el dataframe
df_cate.dtypes

[String, Categorical(ordering='physical')]

In [94]:
# Schema de los datos
df_cate.schema

Schema([('Fruta', String), ('Fruta2', Categorical(ordering='physical'))])

In [95]:
# Crear los datos categoricos desde a declaracion de los datos
df_cate = pl.DataFrame({
    'A': pl.Series(list('abca')).cast(pl.Categorical),
    'B': pl.Series(list('bccd')).cast(pl.Categorical)
})
df_cate

shape: (4, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ cat ┆ cat │
╞═════╪═════╡
│ a   ┆ b   │
│ b   ┆ c   │
│ c   ┆ c   │
│ a   ┆ d   │
└─────┴─────┘

In [96]:
df_cate.dtypes

[Categorical(ordering='physical'), Categorical(ordering='physical')]

In [97]:
df_cate.describe()

shape: (9, 3)
┌────────────┬──────┬──────┐
│ statistic  ┆ A    ┆ B    │
│ ---        ┆ ---  ┆ ---  │
│ str        ┆ str  ┆ str  │
╞════════════╪══════╪══════╡
│ count      ┆ 4    ┆ 4    │
│ null_count ┆ 0    ┆ 0    │
│ mean       ┆ null ┆ null │
│ std        ┆ null ┆ null │
│ min        ┆ null ┆ null │
│ 25%        ┆ null ┆ null │
│ 50%        ┆ null ┆ null │
│ 75%        ┆ null ┆ null │
│ max        ┆ null ┆ null │
└────────────┴──────┴──────┘

## Categóricos Ordinales