# POLARS - Manipulación de datos con Python

[Polars](https://pola.rs/) es una biblioteca de manipulación de datos de alto rendimiento desarrollada por [Ritchie Vink](https://www.linkedin.com/in/ritchievink/). Inicialmente, Polars fue diseñado para ofrecer una alternativa más rápida y eficiente a pandas, utilizando técnicas modernas de procesamiento paralelo y optimización de memoria. Polars está escrito en Rust, lo que le permite manejar grandes volúmenes de datos de manera eficiente y segura, aprovechando al máximo los recursos del hardware disponible.

Los principales tipos de datos que pueden representarse con Polars son:

* Datos tabulares con columnas de tipo heterogéneo con etiquetas en columnas y filas.
* Series temporales.

Polars proporciona herramientas que permiten:

* Leer y escribir datos en diferentes formatos: CSV, JSON, Parquet y más.
* Seleccionar y filtrar tablas de datos de manera sencilla en función de posición, valor o etiquetas.
* Fusionar y unir datos.
* Transformar datos aplicando funciones tanto globalmente como por ventanas.
* Manipulación de series temporales.
* Hacer gráficas.

En Polars existen 2 tipos básicos de objetos:

* Series (listas, 1D)
* DataFrame (tablas, 2D)

Polars nos proporciona las estructuras de datos y funciones necesarias para el análisis de datos de una manera eficiente y rápida, aprovechando las ventajas del procesamiento paralelo y la optimización de memoria. Esto hace que Polars sea una excelente opción para proyectos que requieren manejar grandes volúmenes de datos y realizar análisis complejos de manera eficiente.

<div class="alert alert-success">

<b>La filosofia de polars es en general:</b>

* Utilice todos los núcleos del procesador disponibles en tu máquina.
* Optimizar las consultas para reducir el trabajo innecesario y las asignaciones de memoria.
* Maneje datos mucho más grandes que la RAM disponible en la maquina.

</div>

Si consideras que ya sabes usar pandas, lo más recomendable es entender las diferencias entre Polars y Pandas. Para ello, se sugiere la siguiente lectura:

* https://docs.pola.rs/user-guide/migration/pandas/

## Diferencias principales entre Polars y Pandas

| **Aspecto**                 | **Pandas**                                                                                                                                                                                   | **Polars**                                                                                                                                                                                                           |
|-----------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Lenguaje subyacente**     | Construido originalmente sobre Python y NumPy (C en parte), pero la gestión de memoria puede verse limitada por la forma en la que Python maneja ciertos tipos de datos (por ejemplo, categóricos).                              | Escrito en Rust, lo que permite un control más eficiente de la memoria y un mejor aprovechamiento del hardware, similar a la velocidad de C o C++.                                                                    |
| **Rendimiento**             | Generalmente más lento cuando se trabaja con grandes volúmenes de datos o tipos de datos categóricos (pueden presentarse cuellos de botella en operaciones masivas).                                                              | Excelente rendimiento en operaciones intensivas gracias al paralelismo automático y la optimización interna, logrando procesar millones de filas de forma más veloz.                                                  |
| **Backend / Formato interno** | Pandas (hasta la versión 1.x) usaba principalmente estructuras basadas en NumPy. Con Pandas 2.0, adopta Arrow, pero usando la paquetería Pyarrow.                                                                                  | Utiliza Arrow como base, pero implementado directamente en Rust. Esto brinda gran interoperabilidad y estandarización de memoria, a la vez que mantiene un alto desempeño.                                            |
| **Evaluación**              | Evaluación inmediata (eager): cada operación se ejecuta al momento, lo que puede generar gastos computacionales repetidos (parciales) en la misma cadena de transformaciones.                                                     | Ofrece evaluación diferida (lazy), lo que acumula y optimiza las operaciones antes de ejecutarlas, reduciendo de manera significativa el tiempo total de procesamiento.                                               |
| **Uso de memoria**          | Puede ser más propenso a utilizar grandes cantidades de memoria en operaciones complejas y grandes volúmenes de datos.                                                                                                            | Maneja la memoria de forma más eficiente y optimizada, reduciendo la probabilidad de cuellos de botella y aprovechando mejor la RAM disponible.                                                                      |
| **Ecosistema y madurez**    | Amplio soporte y popularidad: muy integrado con librerías como scikit-learn, matplotlib, etc. Es la herramienta estándar para muchas tareas de análisis de datos en Python.                                                      | Cada vez más popular, en rápido desarrollo y con buena documentación. Ofrece integración creciente con otras librerías y se perfila como una alternativa robusta para el análisis de datos de alto rendimiento.         |

## Importando Polars

In [1]:
import polars as pl
import numpy as np

## Series

Una serie es el primer tipo de datos de Polars y es similar a una matriz NumPy. Lo que diferencia una matriz NumPy de una serie en Polars es que una serie puede tener etiquetas en los ejes, lo que significa que puede ser indexada por una etiqueta, en lugar de solo una ubicación numérica. Además, no necesita contener datos numéricos; puede contener cualquier objeto arbitrario compatible con Polars. Las series en Polars están diseñadas para ser eficientes y rápidas, aprovechando el rendimiento de Rust para manejar grandes volúmenes de datos de manera eficiente.

### Creando una Serie

Puede convertir una lista, una matriz numpy o un diccionario en una serie, usando el método pl.Series:

In [2]:
# Crear diferentes tipos de datos
labels = ['a','b','c'] # lista de etiquetas
my_list = [10,20,30] # lista con valores
arr = np.array([10,20,30]) # Convertir ista de valores en arreglo NumPy

In [3]:
# Convertir una lista en series usando el método pl.Series
# observe que se crean los nombres con las posiciones de cada elemento
pl.Series(values=my_list)

shape: (3,)
Series: '' [i64]
[
	10
	20
	30
]

In [4]:
# Convertir una lista en series usando el método pl.Series
# se puede ingresar el nombre de la serie
pl.Series(name= "numeros" ,values=my_list)

shape: (3,)
Series: 'numeros' [i64]
[
	10
	20
	30
]

In [5]:
# No es necesario ingresar la palabra de 'values =''  en el argumento
# Convertir una lista en series usando el método pl.Series
# se puede ingresar el nombre de la serie
pl.Series(my_list)

shape: (3,)
Series: '' [i64]
[
	10
	20
	30
]

In [6]:
# Desde Arreglos NumPy
# Convertir un arreglo en series usando el método pl.Series
pl.Series(arr)

shape: (3,)
Series: '' [i64]
[
	10
	20
	30
]

In [7]:
# Convertir un arreglo en series indicando también el nombre
pl.Series("numpy",arr)

shape: (3,)
Series: 'numpy' [i64]
[
	10
	20
	30
]

In [8]:
# Creando una serie basado solo en una lista de letras
pl.Series(values=labels)

shape: (3,)
Series: '' [str]
[
	"a"
	"b"
	"c"
]

### Indexación

Es diferente que pandas, Polars no utiliza un índice y cada fila se indexa por su posición entera en la tabla.

Veamos un ejemplo:

In [9]:
ser1 = pl.Series([1,2,3,4])

In [10]:
ser2 = pl.Series([1,2,5,4])

In [11]:
ser1[0]

1

In [12]:
ser1[3]

4

Las operaciones también se realizan según el índice:

In [13]:
ser1 + ser2

shape: (4,)
Series: '' [i64]
[
	2
	4
	8
	8
]

## DataFrames

Los DataFrames son la estructura mas importante en polars y están directamente inspirados en el lenguaje de programación R. Se puede pensar en un DataFrame como un conjunto de Series reunidas. En los DataFrame tenemos la opción de especificar tanto el columns (el nombre de las columnas).

In [14]:
# Importar la función de NumPy para crear arreglos de números enteros
from numpy.random import randn

np.random.seed(101) # Inicializar el generador aleatorio
# Crear un dataframe con números aleatorios de 4 Columnas y 5 Filas
# Esto evita tener que escribir repetidamente las comas

df = pl.DataFrame(
    {
        "W": randn(6),
        "X": randn(6),
        "Y": randn(6),
        "Z": randn(6)
    }
)
df

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

### Descripción general del DataFrame

In [15]:
# Número de filas y columnas

df.shape

(6, 4)

In [16]:
# Información general de los datos

df.collect_schema()

Schema([('W', Float64), ('X', Float64), ('Y', Float64), ('Z', Float64)])

In [17]:
# Solo ver los tipos de datos que existen en las columnas del dataframe

df.dtypes

[Float64, Float64, Float64, Float64]

### Resumen de estadística general

In [18]:
df.describe()

shape: (9, 5)
┌────────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ W         ┆ X         ┆ Y         ┆ Z         │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 6.0       ┆ 6.0       ┆ 6.0       ┆ 6.0       │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 0.84643   ┆ -0.263391 ┆ 0.270199  ┆ 0.403443  │
│ std        ┆ 1.002706  ┆ 1.087891  ┆ 1.087051  ┆ 1.642939  │
│ min        ┆ -0.319318 ┆ -2.018168 ┆ -0.933237 ┆ -1.706086 │
│ 25%        ┆ 0.503826  ┆ -0.848077 ┆ -0.758872 ┆ -1.159119 │
│ 50%        ┆ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ 0.683509  │
│ 75%        ┆ 0.907969  ┆ 0.605965  ┆ 0.955057  ┆ 1.693723  │
│ max        ┆ 2.70685   ┆ 0.740122  ┆ 1.978757  ┆ 2.605967  │
└────────────┴───────────┴───────────┴───────────┴───────────┘

In [19]:
# Ver primeros elementos del dataframe

df.head(3)

shape: (3, 4)
┌──────────┬───────────┬───────────┬──────────┐
│ W        ┆ X         ┆ Y         ┆ Z        │
│ ---      ┆ ---       ┆ ---       ┆ ---      │
│ f64      ┆ f64       ┆ f64       ┆ f64      │
╞══════════╪═══════════╪═══════════╪══════════╡
│ 2.70685  ┆ -0.848077 ┆ 0.188695  ┆ 2.605967 │
│ 0.628133 ┆ 0.605965  ┆ -0.758872 ┆ 0.683509 │
│ 0.907969 ┆ -2.018168 ┆ -0.933237 ┆ 0.302665 │
└──────────┴───────────┴───────────┴──────────┘

In [20]:
# Ver últimos elementos

df.tail(4)

shape: (4, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

In [21]:
# Ver elementos aleatorios

df.sample(3)

shape: (3, 4)
┌──────────┬───────────┬───────────┬───────────┐
│ W        ┆ X         ┆ Y         ┆ Z         │
│ ---      ┆ ---       ┆ ---       ┆ ---       │
│ f64      ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╡
│ 0.651118 ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ 0.907969 ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826 ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
└──────────┴───────────┴───────────┴───────────┘

### Selección e Indexación

In [22]:
df["W"]

shape: (6,)
Series: 'W' [f64]
[
	2.70685
	0.628133
	0.907969
	0.503826
	0.651118
	-0.319318
]

In [23]:
df[['W', 'Z']]

shape: (6, 2)
┌───────────┬───────────┐
│ W         ┆ Z         │
│ ---       ┆ ---       │
│ f64       ┆ f64       │
╞═══════════╪═══════════╡
│ 2.70685   ┆ 2.605967  │
│ 0.628133  ┆ 0.683509  │
│ 0.907969  ┆ 0.302665  │
│ 0.503826  ┆ 1.693723  │
│ 0.651118  ┆ -1.706086 │
│ -0.319318 ┆ -1.159119 │
└───────────┴───────────┘

In [24]:
df[['X', 'W', 'Z']]

shape: (6, 3)
┌───────────┬───────────┬───────────┐
│ X         ┆ W         ┆ Z         │
│ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╡
│ -0.848077 ┆ 2.70685   ┆ 2.605967  │
│ 0.605965  ┆ 0.628133  ┆ 0.683509  │
│ -2.018168 ┆ 0.907969  ┆ 0.302665  │
│ 0.740122  ┆ 0.503826  ┆ 1.693723  │
│ 0.528813  ┆ 0.651118  ┆ -1.706086 │
│ -0.589001 ┆ -0.319318 ┆ -1.159119 │
└───────────┴───────────┴───────────┘

Las columnas de un dataframe son solo series

In [25]:
type(df['W'])

polars.series.series.Series

### Creación de nueva columna

Se realiza con el método `.with.columns()` y el nombre de la nueva columna se realiza con el método `.alias()`

In [26]:
# Nueva columnas igual a la suma de otras dos
# Operación vectorizada

df = df.with_columns((df["W"] + df["Y"]).alias("New W+Y"))

In [27]:
df

shape: (6, 5)
┌───────────┬───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         ┆ New W+Y   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  ┆ 2.895545  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  ┆ -0.130739 │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  ┆ -0.025268 │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  ┆ 1.458882  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 ┆ 0.841912  │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 ┆ 1.659439  │
└───────────┴───────────┴───────────┴───────────┴───────────┘

In [28]:
# Eliminando columnas

df.drop("New W+Y")

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

In [29]:
# Nótese que no se aplica al dataframe, a menos que se especifique

df

shape: (6, 5)
┌───────────┬───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         ┆ New W+Y   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  ┆ 2.895545  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  ┆ -0.130739 │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  ┆ -0.025268 │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  ┆ 1.458882  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 ┆ 0.841912  │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 ┆ 1.659439  │
└───────────┴───────────┴───────────┴───────────┴───────────┘

In [30]:
# Para que quede grabado, se debe asignar el resultado

df = df.drop('New W+Y')
df

shape: (6, 4)
┌───────────┬───────────┬───────────┬───────────┐
│ W         ┆ X         ┆ Y         ┆ Z         │
│ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.70685   ┆ -0.848077 ┆ 0.188695  ┆ 2.605967  │
│ 0.628133  ┆ 0.605965  ┆ -0.758872 ┆ 0.683509  │
│ 0.907969  ┆ -2.018168 ┆ -0.933237 ┆ 0.302665  │
│ 0.503826  ┆ 0.740122  ┆ 0.955057  ┆ 1.693723  │
│ 0.651118  ┆ 0.528813  ┆ 0.190794  ┆ -1.706086 │
│ -0.319318 ┆ -0.589001 ┆ 1.978757  ┆ -1.159119 │
└───────────┴───────────┴───────────┴───────────┘

### Obtener los nombres de las columnas y los indices (index)

#### Seleccionando Filas y Columnas

Las dos formas de selección principal son:

1. Usando `[]`
    * DataFrame[etiqueta_columna] <- por etiquetas de las columnas
    * DataFrame[indice_fila, indice_columna] <- por indices

2. Usando expresiones como `filter`, `select` and `with_columns`

    * Usa filter cuando necesites filtrar filas basadas en condiciones.
    * Usa select cuando necesites seleccionar y/o transformar columnas.
    * Usa with_columns cuando necesites añadir o modificar una o más columnas en el DataFrame. Puedes crear nuevas columnas o actualizar las existentes basándote en expresiones.

In [31]:
df['Z']

shape: (6,)
Series: 'Z' [f64]
[
	2.605967
	0.683509
	0.302665
	1.693723
	-1.706086
	-1.159119
]

In [32]:
df.head(1)

shape: (1, 4)
┌─────────┬───────────┬──────────┬──────────┐
│ W       ┆ X         ┆ Y        ┆ Z        │
│ ---     ┆ ---       ┆ ---      ┆ ---      │
│ f64     ┆ f64       ┆ f64      ┆ f64      │
╞═════════╪═══════════╪══════════╪══════════╡
│ 2.70685 ┆ -0.848077 ┆ 0.188695 ┆ 2.605967 │
└─────────┴───────────┴──────────┴──────────┘

In [33]:
# O basado en la posición en vez de usar la etiqueta

df[:,2]

shape: (6,)
Series: 'Y' [f64]
[
	0.188695
	-0.758872
	-0.933237
	0.955057
	0.190794
	1.978757
]

### Seleccionar un subconjunto de filas y columnas

In [34]:
# Mediante etiquetas
# Se selecciona el elemento que está en la fila=1 col=Y
df[1, 'Y']

-0.758872056210466